### ISSUE TITLE
HMSegmentedControlSelectionStyleTextWidthStripe and HMSegmentedControlSelectionStyleBox at the same time

### ISSUE THREAD

**Issue by gyifr** [HeshamMegid/HMSegmentedControl#100]
Hi, I'd like to have both of these styles at the same time, that is, a selected tab with the Indicator width that cover only the text and a rectangle background that covers the whole selected segment.
Can you help me? Thanks.

**Comment by HeshamMegid** [comment]
Closing for now since this is very old. Feel free to reopen if you still need help.
