### ISSUE TITLE
can't make this work on swift app

### ISSUE THREAD

**Issue by mirzadelic** [HeshamMegid/HMSegmentedControl#103]
Installed with pod, and now i have this controller:
```
import UIKit
import HMSegmentedControl

class MainViewController: UIViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        var segmentedControl: HMSegmentedControl  = HMSegmentedControl(sectionTitles: ["One", "Two"])
        segmentedControl.frame = CGRectMake(10, 10, 300, 60)
        segmentedControl.addTarget(self, action: "segmentedControlChangedValue:", forControlEvents: UIControlEvents())
        self.view.addSubview(segmentedControl)
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
}
```
But nothing happens, when i start app i get white app without segmented control.

What am i doing wrong here?

This is happening with other packages, when i try to use them in my app, maybe i need something to setup?

**Comment by benjaminhorner** [comment]
This is unrelated to HMSegmentedControl. You should post your question on stackoverflow with a little more code and detail.

**Comment by tunidev** [comment]
The segmented control in under the navigation bar like that, just  try `segmentedControl.frame = CGRectMake(10, 80, 300, 60)` and you should see it, but better than that use autolayout

**Comment by HeshamMegid** [comment]
Doesn't seem like a problem related to HMSegmentedControl, like @benjaminhorner mentioned.
