### ISSUE TITLE
The segmented control to a scroll view

### ISSUE THREAD

**Issue by DeepthiRam** [HeshamMegid/HMSegmentedControl#105]
Hi .. Im using HMSegmentedControl (segmented control to a scroll view) in my app, when im tapping segment controller views are placing correctly, but when im scrolling the views selectedSegmentIndex is showing 1st index could u please look on this ..

Thanks in advance ..
Deepthi

**Comment by leeguoyu** [comment]
the same problem happens to me. I have 2 tableviews on one scrollview. on table 2 (this means the segmented index is 2 as well), if I swipe down or up, the index indicator will move back to 1.

**Comment by leeguoyu** [comment]
Hi, I think I've fixed it. I changed the code above like this.
```
- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView {
//    CGFloat pageWidth = scrollView.frame.size.width;
//    NSInteger page = scrollView.contentOffset.x / pageWidth;
//    [self.segmentedControl setSelectedSegmentIndex:page animated:YES];
    if (self.scrollView.contentOffset.x == viewWidth) {
        [self.segmentedControl setSelectedSegmentIndex:1 animated:YES];
    }else{
        [self.segmentedControl setSelectedSegmentIndex:0 animated:YES];
    }
    
}
```

**Comment by yogeshraz** [comment]
I have 3 table view onscroll. Same problem happen to me.  Do u have solution??

**Comment by jonoljon** [comment]
Set a tag on each tableview and in scrollViewDidEndDecelarting ignore it

Where you set up your tableviews;
self.tableView1.tag = 1000; 
self.tableView2.tag = 2000; 
self.tableView3.tag = 3000;

and

- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView {
    
    if(self.scrollView.tag == 1000)
        return;
    
    else if(self.scrollView.tag == 2000)
        return;
    else if(self.scrollView.tag == 3000)
        return;
}

**Comment by malakiya** [comment]
Hi guys, i had the same problem. The method **scrollViewDidEndDecelerating** it works to UITableView too so, you have to check if you are scrolling the **UITableView** or the **UIScrollView**
 
```
- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView {
    
    if (![scrollView isKindOfClass:[UITableView class]]) {
        
        CGFloat pageWidth = scrollView.frame.size.width;
        
        NSInteger page = scrollView.contentOffset.x / pageWidth;
        
        [self.segmentedControl setSelectedSegmentIndex:page animated:YES];
        
    }
    
}

```

**Comment by HeshamMegid** [comment]
Closing for now since this is very old. Feel free to reopen if you still need help.
