### ISSUE TITLE
Black portions of layout when running HMSegmentedControlExample in the iOS 7.1 simulator

### ISSUE THREAD

**Issue by alexcosmin** [HeshamMegid/HMSegmentedControl#108]
I cloned the repository, and ran the **HMSegmentedControlExample** project in the iOS 7.1 simulator (iPhone 5) and it looks like this:

![ios 7 1](https://cloud.githubusercontent.com/assets/5630100/7552339/1c7e5736-f6af-11e4-8b97-a1628f72f88b.png)

Doing the same on a iOS 8.x simulator works fine:

![ios 8](https://cloud.githubusercontent.com/assets/5630100/7552345/6310493e-f6af-11e4-8b28-cca434711afb.png)

Any idea what could cause this?
I'm using **Xcode 6.3.1**.

**Comment by Vanson** [comment]
Please Add LaunchScreen.xib Or Launch Images

**Comment by alexcosmin** [comment]
@Vanson Thank you, that solved the problem!
