### ISSUE TITLE
Can't make HMSegmentedControlSelectionStyleArrow work with Arrow down

### ISSUE THREAD

**Issue by inPhilly** [HeshamMegid/HMSegmentedControl#111]
I have tried setting the bottom inset on selectionIndicatorEdgeInsets, but I can't get HMSegmentedControlSelectionStyleArrow to display a down arrow no matter what I try. Please advise - is this a bug or am I missing something?

**Comment by cooler333** [comment]
+1

**Comment by HeshamMegid** [comment]
Can you please share the full code you use to configure the control?
