### ISSUE TITLE
Function call argument is an uninitialized value

### ISSUE THREAD

**Issue by mhomam** [HeshamMegid/HMSegmentedControl#112]
From Xcode when I do Product->Analyze, in HMSegmentedControl.m, i get this error at following statement. I am using swift for iOS 7 & iOS 8 supported project.

```
// Fix rect position/size to avoid blurry labels
rect = CGRectMake(ceilf(rect.origin.x), ceilf(rect.origin.y), ceilf(rect.size.width), ceilf(rect.size.height));
```

**Comment by HeshamMegid** [comment]
This should be fixed in the latest release. Feel free to reopen if it's not.
