### ISSUE TITLE
Is there a way to know when a segment is selected even if it's the current one?

### ISSUE THREAD

**Issue by cerupcat** [HeshamMegid/HMSegmentedControl#113]
In the code, it looks like there's a check to see if the touched segment is already the current segment and if so it doesn't send any events that are observable. It'd be nice to have a separate event of some type get send so we can see when a segment is selected regardless whether it's already selected or not. 

Is that already possible?

**Comment by HeshamMegid** [comment]
Sorry for the late reply.

No, that's currently not possible. It's an easy modifications though if you're willing to fork the repo and remove the line that checks if the tapped segment is the currently selected segment.

**Comment by seanLee** [comment]
I have the same using like yours.I don't know how to use github to submit the code well,but you can change the code into this ````if (segment < sectionsCount) {
            // Check if we have to do anything with the touch event
            if (self.isTouchEnabled)
                [self setSelectedSegmentIndex:segment animated:self.shouldAnimateUserSelection notify:YES];
        }````
in the ````HMSegmentedControl.m```` at line 732.
It works for me,maybe it's not the most valuable solution
