### ISSUE TITLE
How to fix: Selected segment is off screen on initial load

### ISSUE THREAD

**Issue by wm-j-ray** [HeshamMegid/HMSegmentedControl#116]
Hesham,

I'm subclassing the segmentedControl in a storyboard environment with a total number of segments too wide for portrait so some of the available segments are out of frame in the control's scrollView.

When I pass in the initial selected segment to the viewController on initialization if the selected segment is out of frame, I'd like to ensure the selected segment is in frame.  I've tried

```
 - (void)setSelectedSegmentIndex:(NSUInteger)index animated:(BOOL)animated;
```

with no success.  Since the actual scrollView is private I don't know the best way to set the content offset to solve the problem.

Any pointers or assistance are greatly appreciated and thank you for sharing this nice piece of code.

**Comment by HeshamMegid** [comment]
This should be fixed in the latest release. Feel free to reopen if it's not.
