### ISSUE TITLE
Vertical scrolling when using HMSegmentedControl

### ISSUE THREAD

**Issue by manjubasha** [HeshamMegid/HMSegmentedControl#119]
Hi,
   I have two scrollviews here. They are nested. The hierarchy of the view i have designed is as follows

![screen shot 2015-06-22 at 3 37 04 pm](https://cloud.githubusercontent.com/assets/817986/8279743/99493544-18f4-11e5-9c80-9348f8b05e51.png)

My 2nd and 4th segments have very large text to be show which needs vertical scrolling. So i nested the scrollview for 2nd and 4th segment with HMSegment's scrollview. I am not able to achieve vertical scroll for my 2nd and 4th segment content. Is there anything i am missing out?

**Comment by HeshamMegid** [comment]
Closing for now since this is very old. Feel free to reopen if you still need help.
