### ISSUE TITLE
Accessibility label for HMSegmentedControl

### ISSUE THREAD

**Issue by popei69** [HeshamMegid/HMSegmentedControl#120]
Is there a way to use accessibilitylabel for HMSegmentedControl?

I would like to use it in UIAutomation.

**Comment by pedro380085** [comment]
Not really, @HeshamMegid uses a `CATextLayer` instead of a `UILabel`.

http://stackoverflow.com/questions/13254122/ios-accessibility-label-for-calayer

**Comment by HeshamMegid** [comment]
As @pedro380085 said, no there isn't.

I'm thinking of replacing the `CATextLayers` with `UILabels` though, I believe it would make many things much easier for upcoming versions.

**Comment by vidhi110** [comment]
@HeshamMegid I would like to use accessibilitylabel too for automation and was wondering if there is any upcoming plan to replace CATextLayers with UILabels ? 

Thanks
