### ISSUE TITLE
ios 9 crash loading STHeitisSC-Light font

### ISSUE THREAD

**Issue by pmaccamp** [HeshamMegid/HMSegmentedControl#121]
I'm encountering the following crash in a very small number of users
`-[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0] `

with the stacktrace

	0x00000001002d019c -[HMSegmentedControl resultingTitleTextAttributes] (HMSegmentedControl.m:860)
	0x00000001002d02c4 -[HMSegmentedControl resultingSelectedTitleTextAttributes] (HMSegmentedControl.m:875)
	0x00000001002cb0b0 -[HMSegmentedControl measureTitleAtIndex:] (HMSegmentedControl.m:223)
	0x00000001002cd984 -[HMSegmentedControl frameForSelectionIndicator] (HMSegmentedControl.m:544)
	0x00000001002cd420 -[HMSegmentedControl setArrowFrame] (HMSegmentedControl.m:497)
	0x00000001002cfa7c -[HMSegmentedControl setSelectedSegmentIndex:animated:notify:] (HMSegmentedControl.m:835)

Looking at the source it seems like the STHeitisSC-Light font is not getting loaded correctly
``` 
NSDictionary *defaults = @{
	NSFontAttributeName : [UIFont fontWithName:@"STHeitiSC-Light" size:18.0f],
	NSForegroundColorAttributeName : [UIColor blackColor],
}; 
```

In writing this I just noticed all 3 crashes occurred on users with iOS 9 so that's almost certainly the cause.  I'm guessing the font was renamed or removed.

**Comment by sdgroot** [comment]
I'm seeing the same crash in the reports since a few days. I'm also using a custom font and it only crashes for iOS 9 users.

**Comment by izuchy** [comment]
> Looking at the source it seems like the STHeitisSC-Light font is not getting loaded correctly

It succeeded by changing the font . Well in this font specified bad .
Thank you.

**Comment by HeshamMegid** [comment]
For some reason the whole Heiti SC font family is missing in iOS 9.

I've updated the code to use the default system font. Please update your pod to 1.5.2.
