### ISSUE TITLE
set UINavigationBar.appearance().translucent 

### ISSUE THREAD

**Issue by HanTsing** [HeshamMegid/HMSegmentedControl#122]
Hi, Im using HMSegmentedControl in my app.  when i set  "UINavigationBar.appearance().translucent = false" in didFinishLaunchingWithOptions,  the position of HMSegmentedControl has changed 
  
![8735edb3-62a7-4b88-b1f7-e1dc45ae4c30](https://cloud.githubusercontent.com/assets/1274305/8537577/9db8b7f8-2493-11e5-955a-c42447a04e2a.png)
Thanks in advance ..
HanQing

**Comment by HeshamMegid** [comment]
This isn't related to the segmented control. When view controllers have a non-translucent navigation bar, they will layout out their view at y = 64.
