### ISSUE TITLE
ambiguous title text size with custom font

### ISSUE THREAD

**Issue by DenDoronin** [HeshamMegid/HMSegmentedControl#124]
Hi. i have the following problem:

when i set up my segment control with titleTextAttributes like so:

```
self.segmentedControl.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor],
                                              NSFontAttributeName : [UIFont fontWithName:@"ProximaNova-Light" size:15.0]
                                              };
```

i've got this result

<img width="374" alt="screen shot 2015-07-17 at 3 25 35 pm" src="https://cloud.githubusercontent.com/assets/3168299/8747105/875a7f20-2c98-11e5-8576-93423fb1cbc2.png">

but when i use 
self.segmentedControl.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor],
                                                   NSFontAttributeName : [UIFont systemFontOfSize:15.0]
                                                  };

everything is great:

<img width="377" alt="screen shot 2015-07-17 at 3 26 02 pm" src="https://cloud.githubusercontent.com/assets/3168299/8747118/a75fcf1e-2c98-11e5-9610-532f834c4a3f.png">

How can i fix this? 

the full code snippet for init:

 CGRect screenRect = [[UIScreen mainScreen] bounds];
    CGFloat screenWidth = screenRect.size.width;

```
self.segmentedControl= [[HMSegmentedControl alloc] initWithFrame:CGRectMake(0, 0, screenWidth, self.segmentControlPlacement.frame.size.height)];
self.segmentedControl.backgroundColor = RGBA(50, 53, 60, 0.3*255);
self.segmentedControl.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor],
                                              NSFontAttributeName : [UIFont fontWithName:@"ProximaNova-Light" size:15.0]
                                              };

self.segmentedControl.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor],
                                               NSFontAttributeName : [UIFont systemFontOfSize:15.0]
                                              };
self.segmentedControl.selectionIndicatorColor = RGBA(50, 53, 60, 255);
self.segmentedControl.selectionStyle = HMSegmentedControlSelectionStyleBox;
self.segmentedControl.selectedSegmentIndex = HMSegmentedControlNoSegment;
self.segmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationNone;

self.segmentedControl.segmentEdgeInset = UIEdgeInsetsMake(0, 10, 0, 10);

self.segmentedControl.segmentWidthStyle = HMSegmentedControlSegmentWidthStyleFixed;
self.segmentedControl.shouldAnimateUserSelection = NO;
self.segmentedControl.verticalDividerEnabled = YES;
self.segmentedControl.verticalDividerColor = RGBA(50, 53, 60, 255);
self.segmentedControl.verticalDividerWidth = 1.0f;

[self.segmentControlPlacement addSubview:self.segmentedControl];
```

**Comment by jerrypainter** [comment]
same problem here. When i use custom font, part of the titles are covered. Works great when using system font

**Comment by DenDoronin** [comment]
@jerrypainter , i 've found the working solution. the problem was in 

- (CGSize)measureTitleAtIndex:(NSUInteger)index

this line -> size = [(NSString *)title sizeWithAttributes:titleAttrs];
Size was calculated in a wrong way. so, i just add the following line of code:

size = CGSizeMake(ceil(size.width)+1, ceil(size.height));

The full method:

- (CGSize)measureTitleAtIndex:(NSUInteger)index {
    id title = self.sectionTitles[index];
    CGSize size = CGSizeZero;
    BOOL selected = (index == self.selectedSegmentIndex) ? YES : NO;
    if ([title isKindOfClass:[NSString class]] && !self.titleFormatter) {
        NSDictionary *titleAttrs = selected ? [self resultingSelectedTitleTextAttributes] : [self resultingTitleTextAttributes];
        size = [(NSString *)title sizeWithAttributes:titleAttrs];
        size = CGSizeMake(ceil(size.width)+1, ceil(size.height));
    } else if ([title isKindOfClass:[NSString class]] && self.titleFormatter) {
        size = [self.titleFormatter(self, title, index, selected) size];
    } else if ([title isKindOfClass:[NSAttributedString class]]) {
        size = [(NSAttributedString *)title size];
    } else {
        NSAssert(title == nil, @"Unexpected type of segment title: %@", [title class]);
        size = CGSizeZero;
    }
    return CGRectIntegral((CGRect){CGPointZero, size}).size;
}

**Comment by HeshamMegid** [comment]
This should be fixed in the latest release. Feel free to reopen if it's not.

**Comment by chandra-news-distill** [comment]
Still i have a issue with custom fonts with height
