### ISSUE TITLE
How to change selected index title color alone?

### ISSUE THREAD

**Issue by karthisiva** [HeshamMegid/HMSegmentedControl#125]
I trying to change title color of selected index only but i cant find any property for that.is there any property? give us sample code

 HMSegmentedControl *segmentedControl3 = [[HMSegmentedControl alloc] initWithSectionTitles:@[@"One", @"Two", @"Three", @"4", @"Five"]];
    [segmentedControl3 setFrame:CGRectMake(0, 180, viewWidth, 50)];
[segmentedControl3 setIndexChangeBlock:^(NSInteger index) {
        if (index==0) {
            segmentedControl3.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor orangeColor]};
        }

```
}];
```

Its changing all the title color.

**Comment by karthisiva** [comment]
oh my bad i didnt see this property

 [headerBar setIndexChangeBlock:^(NSInteger index) {
        NSLog(@"Selected index %ld (via block)", (long)index);
        headerBar.selectedTitleTextAttributes=@{NSForegroundColorAttributeName : [UIColor greenColor]};
    }];

i have ended with this code..

**Comment by pedro380085** [comment]
@karthisiva Would you mind closing this issue?
