### ISSUE TITLE
Borders do not span width of HMSegmentedControl

### ISSUE THREAD

**Issue by jwardle** [HeshamMegid/HMSegmentedControl#126]
If there are multiple items on the HMSegmentedControl - so that it ends up enabling scrolling as they cannot fit on the width of the screen, then the border applied using HMSegmentedControl.border\* properties only seem to apply to the individual segments, rather than the underlying segmented control. This means that if bounce is enabled then and the user scrolls 'too far' to the left or right then there is a gap in the border from the nearest item (to the edge of the screen) to the actual edge of the screen.

One can add a border to the HMSegmentedControl view however this can show below the selected segment indicator and provide unattractive results.

**Comment by HeshamMegid** [comment]
Can you please share code that shows this issue?
