### ISSUE TITLE
Segment Badge

### ISSUE THREAD

**Issue by pedro380085** [HeshamMegid/HMSegmentedControl#129]
It would be a great idea to have the possibility to add a number as a badge on each segment. Something similar to what is done on a typical tab bar.

**Comment by ezrasuki** [comment]
+1

**Comment by khoren93** [comment]
+1

**Comment by altair21** [comment]
+1

**Comment by pedro380085** [comment]
@HeshamMegid There is any further updates to the project? Thanks,

**Comment by HeshamMegid** [comment]
Hi @pedro380085, I'm no longer working on updating this project, however, I'm working on a new Swift version at https://github.com/HeshamMegid/HMSegmentedControl-Swift. It's still a work in progress, but you'll find the code base much easier to work with, so feel free to fork it, add the badge and create a pull request, and I'll be happy to merge it.
