### ISSUE TITLE
segmented control that just changes color of text/title of active segment

### ISSUE THREAD

**Issue by nickthedude** [HeshamMegid/HMSegmentedControl#130]
Is this possible? I'm diving into the code a bit, and looks like maybe I could do it with attributed strings, but not sure. If this is trivial for you to add would be a nice feature and in line with the "new" (iOS 7) button style.

Thanks.

**Comment by nickthedude** [comment]
eh nevermind figured out how to achieve it with the stock UISegmentedControl. Thanks for reading though.

**Comment by HeshamMegid** [comment]
:+1:
