### ISSUE TITLE
scrolling the selectionIndicator

### ISSUE THREAD

**Issue by tospery** [HeshamMegid/HMSegmentedControl#131]
In demo, when i scrolling the self.scrollView, how can i let the self.segmentedControl4's selectionIndicator is scrolling also.

**Comment by pedro380085** [comment]
I didn't quite get what you're asking. You want to scroll the segmentControl?

**Comment by chetan77** [comment]
scrolling not work when pass dynamic data ti title .Any solution for this.

**Comment by HeshamMegid** [comment]
Not sure what you mean. Closing for now. Feel free to reopen with more details.
