### ISSUE TITLE
How To Delete or Add Segments Dynamically 

### ISSUE THREAD

**Issue by kmuddapu** [HeshamMegid/HMSegmentedControl#133]
Thanks for the Controller  :)

I am using table view under Segments. When I am  trying to delete data in table view at that time i need to delete Segment with no data. 

Thanks in advance ..
Kalyan

**Comment by firuz1844** [comment]
Try just set sectionTitles property and then ask setNeedsLayout. Like here:
        self.segment.sectionTitles = @[@"A", @"B", @"C"];
        [self.segment setNeedsDisplay];

**Comment by chetan77** [comment]
how to pass dynamic data to HMSegmentedControl . i try to pass array but only data show , scrolling not work Please give me any suggestion

**Comment by HeshamMegid** [comment]
You should be able to do that the way @firuz1844 indicated.
