### ISSUE TITLE
How can I set an Attributed String for a section title and then edit the attributes for a selected segment

### ISSUE THREAD

**Issue by halpz** [HeshamMegid/HMSegmentedControl#135]
<img width="363" alt="screen shot 2015-08-27 at 13 56 33" src="https://cloud.githubusercontent.com/assets/3755417/9520960/75b5ab1e-4cc3-11e5-9ee3-d7c3c2a8a154.png">

The left segment is an NSAttributedString, but I cannot edit the attributes when selected unlike the regular NSString segments beside it

**Comment by pedro380085** [comment]
You have a property `selectedTitleTextAttributes` where you can edit these attributes.

**Comment by benjaminhorner** [comment]
How did you get the NSAttributed string to work ? I am trying to get exactly the same layout (well almost) as you and I get the following crash : -[NSConcreteAttributedString _fastCharacterContents]

**Comment by tahseen0amin** [comment]
Has anybody solved this yet ??

**Comment by HeshamMegid** [comment]
Hey everyone, please check the Swift version of HMSegmentedControl at https://github.com/HeshamMegid/HMSegmentedControl-Swift/
