### ISSUE TITLE
Make selected tab background color independent of selectionIndicatorColor

### ISSUE THREAD

**Issue by tp** [HeshamMegid/HMSegmentedControl#139]
Currently it seems that the active tabs color is a lighter version of `selectionIndicatorColor`.

As I have not found a way to change the `SelectionIndicator`s color separately from the active tabs background, I create this tracking issue.

If you're currently busy I might have a try at this myself, though I have not written Objective C in a long time.

**Comment by HeshamMegid** [comment]
I believe you're talking about using the control with a `selectionStyle` equal to `HMSegmentedControlSelectionStyleBox`, right?

If so, then yes there's no way to customize the selection color, but you can customize its opacity using `selectionIndicatorBoxOpacity`.

If you'd like to have a go at it and send a pull request, that would be highly appreciated.

**Comment by federicocappelli** [comment]
@HeshamMegid pull request submitted [https://github.com/HeshamMegid/HMSegmentedControl/pull/159]

**Comment by HeshamMegid** [comment]
Merged #159.
