### ISSUE TITLE
Configurable vertical divider height

### ISSUE THREAD

**Issue by tp** [HeshamMegid/HMSegmentedControl#140]
It seems like the vertical divider height is currently fixed.

I think it would make sense to allow full-height dividers for example, therefore this should be configurable in my opinion.

**Comment by HeshamMegid** [comment]
Makes sense. I'll include this in a future version.

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. 

If you'd still like to see this, feel free to open a PR.
