### ISSUE TITLE
Debug View Hierarchy Causing Crash

### ISSUE THREAD

**Issue by Snwspeckle** [HeshamMegid/HMSegmentedControl#142]
It seems that when you try and debug the view hierarchy, the HMScrollView is causing the following error (the view is also not rendered):

```
-[__NSCFType encodeWithCoder:]: unrecognized selector sent to instance 0x7fd3e2a73ea0
-[NSCoder(CACoderAdditions) CA_encodeObject:forKey:conditional:]: ignoring exception -[__NSCFType encodeWithCoder:]: unrecognized selector sent to instance 0x7fd3e2a73ea0
-[__NSCFType encodeWithCoder:]: unrecognized selector sent to instance 0x7fd3e2930360
-[NSCoder(CACoderAdditions) CA_encodeObject:forKey:conditional:]: ignoring exception -[__NSCFType encodeWithCoder:]: unrecognized selector sent to instance 0x7fd3e2930360
```

I've tracked the issue down to something being wrong with the HMScrollView. By commenting out

``` objective-c
[self addSubview:self.scrollView];
```

on line 131 of HMSegmentedControl.m, you're able to debug the view hierarchy without the error being thrown.

**Comment by mmarshak** [comment]
I also have this problem, any solution ?

**Comment by mmarshak** [comment]
With the workaround I can not see the segement on the screen

**Comment by HeshamMegid** [comment]
This is actually a known Xcode issue.
