### ISSUE TITLE
Analyze issue

### ISSUE THREAD

**Issue by Remyoman** [HeshamMegid/HMSegmentedControl#143]
When analyzing builds with this lbrary included I get an issue for HMSegmentedControl.m

Function call argument is an uninitialized value
HMSegmentedControl Line 315.

It would be nice if this could be resolved as it tends to be best practise to be clear of both warnings and analyze issues.

**Comment by HeshamMegid** [comment]
This should be fixed in the latest release. Feel free to reopen if it's not.
