### ISSUE TITLE
HMSegmentedControl.m:645 

### ISSUE THREAD

**Issue by Widehuang** [HeshamMegid/HMSegmentedControl#148]
HMSegmentedControl.m:645 
' else if (self.type == HMSegmentedControlTypeTextImages && HMSegmentedControlSegmentWidthStyleDynamic) ' 
did you mean ' else if (self.type == HMSegmentedControlTypeTextImages && self.segmentWidthStyle ==  HMSegmentedControlSegmentWidthStyleDynamic) '

**Comment by HeshamMegid** [comment]
True! Thanks for spotting that.

**Comment by Widehuang** [comment]
np
