### ISSUE TITLE
Attach Table view with HMSegmentedControl

### ISSUE THREAD

**Issue by yogeshraz** [HeshamMegid/HMSegmentedControl#149]
Hi .. Im using HMSegmentedControl (segmented control to a table view) in my app, when i m tapping segment controller views are placing correctly, but when i m pull   the table Segment Index is push on 0 index..

.

**Comment by HeshamMegid** [comment]
I'm not sure what you mean, but my guess is you place the segmented control inside a table view cell and when the cell is reused after scrolling, the segmented control is recreated, so you lose the selected index.
