### ISSUE TITLE
Method touchesBegan: is only called on a "long press"

### ISSUE THREAD

**Issue by lochetti** [HeshamMegid/HMSegmentedControl#15]
I`m testing in a Iphone 4.

If I just tap the area of the segment, the method touchesBegan is not called. I have to do a top of a certain duration to get the method called.

**Comment by btrzupek** [comment]
I had a similar situation and just determine the issue. I have a tapGestureRecognizer on the main view for the ViewController (for keyboard dismisses for another function). That one was eating the events for the segment control.
