### ISSUE TITLE
How to only scroll the Segmented Control horizontally, without the content below it

### ISSUE THREAD

**Issue by radhap** [HeshamMegid/HMSegmentedControl#150]
I have HMSegmentedControl in a view that has a collectionView(which already has vertical scrolling enabled). I want to scroll the HMSegmentedControl horizontally and get the correct setSelectedSegmentIndex and based on that refresh the content of the collectionView. 

Anyway to do this?

I see if I publicly expose the HMScrollView and set the delegate to my viewController then I know I can make it work.. But want to know if there is any other way, without changing the HMSegmentedControl code.

**Comment by HeshamMegid** [comment]
Do you mean changing the index as your scroll horizontally without actually tapping one of the segments?

**Comment by radhap** [comment]
Thank you for responding.. Yes.. Exactly!

**Comment by HeshamMegid** [comment]
The control doesn't support doing that right now, so in all cases you'll have to fork the code.
