### ISSUE TITLE
Swift Example

### ISSUE THREAD

**Issue by mariovillamizar** [HeshamMegid/HMSegmentedControl#153]
Can you provide a example using swift?

**Comment by HeshamMegid** [comment]
Hi @mariovillamizar. Please check the Swift version of HMSegmentedControl at https://github.com/HeshamMegid/HMSegmentedControl-Swift/

**Comment by moonvader** [comment]
**"HMSegmentedControl-Swift currently only has a small subset of the features of HMSegmentedControl, and it's not ready for production use yet."**
