### ISSUE TITLE
Border not showing when setting the type to text and images

### ISSUE THREAD

**Issue by phillebaba** [HeshamMegid/HMSegmentedControl#154]
This happens when you set the type of the segmented control to 
HMSegmentedControlTypeTextImages and the border type to HMSegmentedControlBorderTypeBottom. What has to be noted is that only the firs index contains an image and the rest only have a empty image. The result is that the border is not shown, but when changing the type to only text it is displayed. Anyone have a solution to this?

```
navigationSegment.type = HMSegmentedControlTypeTextImages;
navigationSegment.selectionStyle = HMSegmentedControlSelectionStyleFullWidthStripe;
navigationSegment.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationDown;
navigationSegment.borderType = HMSegmentedControlBorderTypeBottom;
navigationSegment.userDraggable = false;
navigationSegment.selectionIndicatorColor = [UIColor blackColor];
navigationSegment.selectionIndicatorHeight = 2;
navigationSegment.borderColor = [UIColor borderColor];
navigationSegment.borderWidth = 1;
navigationSegment.selectionIndicatorHeight = 3;
[self addSubview:navigationSegment];
```

**Comment by HeshamMegid** [comment]
This should be fixed on the latest release. Please try and it and reopen this issue if you're still having the same problem.
