### ISSUE TITLE
got a warning when use `selectedTitleTextAttributes` and `titleTextAttributes`

### ISSUE THREAD

**Issue by zhou18520786640** [HeshamMegid/HMSegmentedControl#158]
when I use  `selectedTitleTextAttributes` and `titleTextAttributes` as below 

	  segmentedControl.selectedTitleTextAttributes = @{UITextAttributeTextColor:kMainColor,UITextAttributeFont:[UIFont systemFontOfSize:15]};
	    segmentedControl.titleTextAttributes = @{UITextAttributeTextColor:UIColorFromRGB(0x595959),UITextAttributeFont:[UIFont systemFontOfSize:15]};

Xcode tell me  
'UITextAttributeFont' is deprecated: first deprecated in iOS 7.0 - Use NSFontAttributeName

/Users/mix/Desktop/FakeSegmentFault/MIX/MIX/ZZQuestionViewController.m:49:46: 'UITextAttributeTextColor' is deprecated: first deprecated in iOS 7.0 - Use NSForegroundColorAttributeName

should I change the value or  could you fix it by using new api ?  tks!

**Comment by HeshamMegid** [comment]
HMSegmentedControl will apply the attributes dictionary as is, so if you just use `NSFontAttributeName` instead of `UITextAttributeFont`, everything should work fine.
