### ISSUE TITLE
Image to the right of the title

### ISSUE THREAD

**Issue by radhap** [HeshamMegid/HMSegmentedControl#161]
By default the images are added to the left of the title, is there any way to add image to the right of the title?

**Comment by evgeniyd** [comment]
How do you manage to place images to the left ? What settings do you use? Could you please share a screenshot of the final result?

**Comment by radhap** [comment]
You need to use the below init method to create.
- (instancetype)initWithSectionImages:(NSArray *)sectionImages sectionSelectedImages:(NSArray *)sectionSelectedImages titlesForSections:(NSArray *)sectiontitles;

**Comment by evgeniyd** [comment]
the thing is. I looked through the list of issues and believe the code that does just that, is not merged into main repo.

**Comment by radhap** [comment]
I used the main repo only and it worked.

**Comment by nguyenvanbaoanh** [comment]
I want to show image at left of title for every SegmentControl, but couldn't, because the image alway in center of SegmentControl.

**Comment by HeshamMegid** [comment]
That's currently not supported.
