### ISSUE TITLE
Hope to support property that set segment title dynamically

### ISSUE THREAD

**Issue by jordanform** [HeshamMegid/HMSegmentedControl#166]
So love this control!!
However, sometimes segment title may need to change according to event trigger. 
objective-c provide [xxxSegmentControl setTitle:@"Your title" forSegmentAtIndex:0] to do that
If there is a method to achieve that, it will be awesome.

**Comment by HeshamMegid** [comment]
You can set the `sectionTitles` array to update the control, but that will require setting the whole array not just updating one segment.

Feel free to create a pull request with the method you have in mind.

**Comment by r-a-o** [comment]
It doesn't seem to be updating right away, for me its only updating the sectionTitles if I do something on the screen like scroll / touch. @HeshamMegid
