### ISSUE TITLE
Pre Load the next controller

### ISSUE THREAD

**Issue by pvn** [HeshamMegid/HMSegmentedControl#168]
I have three view controller. A, B & C.
The default selected segment is A and want to pre load the controller B (visible controller + 1).

**Comment by khoren93** [comment]
Hi, i recomended see this lib based on HMSegmentedControl (worked pre loading)
https://github.com/maxep/MXSegmentedPager

**Comment by HeshamMegid** [comment]
Closing since this is not directly related to HMSegmentedControl.
