### ISSUE TITLE
How to customize the segment size and the section title font and size - 

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [HeshamMegid/HMSegmentedControl#170]
I am doing a segmented control using HMsegmentedControl. My title for the segments vary in their length. So my question is that Can I change the font as well as can I wordwrap the titles width to length of my content ? You could check my image attached. For eg - I want the width of car segment be wrapped to its length not more than that.
![image](https://cloud.githubusercontent.com/assets/15869731/12230503/2d0ff2e6-b877-11e5-8e64-baed7822a857.png)

**Comment by hackjie** [comment]
hi, @GABHISEKBUNTY did you find any solution?i met too

**Comment by wyangy** [comment]
I'm looking for a solution for this too...

**Comment by GABHISEKBUNTY** [comment]
`segmentedcontrol2.segmentWidthStyle = HMSegmentedControlSegmentWidthStyleDynamic
`

This makes the length of the segments to fit to the character length.

**Comment by hackjie** [comment]
@GABHISEKBUNTY but this can't set the segment's position

**Comment by GABHISEKBUNTY** [comment]
@hackjie  Heyy why don't you create your own segmented control ....

here is my github repo link - [custom segment](https://github.com/GABHISEKBUNTY/customSegment.git)

Please try to unzip that via terminal due to some problem in symlink u can't do it by double clicking.

**Comment by nishantanthwal** [comment]
It supports advanced title styling with text attributes for font, color, kerning, shadow, etc. Try this (and add more attributes if required)

>     _segmentedControl.titleTextAttributes = @{NSFontAttributeName : [UIFont systemFontOfSize:16],
>                                               NSForegroundColorAttributeName : [UIColor redColor]};

**Comment by HeshamMegid** [comment]
Like @nishantanthwal mentioned, you can customize the text attributes using `titleTextAttributes`.
