### ISSUE TITLE
Scroll the segment control to centre always

### ISSUE THREAD

**Issue by pvn** [HeshamMegid/HMSegmentedControl#171]
I have 10 controller but when I say 
pager.pageControl.selectedSegmentIndex = index; (here index is 8) then it loads the right controller but selection of segment is not visible.

I want to scroll the segment to make it in centre.

**Comment by tahoecoop** [comment]
Hello, I am trying to achieve the same, that the selected segment is always centered. Is this possible? Thanks for the assistance!

**Comment by osolano** [comment]
This feature would also benefit what I am currently doing

**Comment by andreichirkunovgoon** [comment]
Me too

**Comment by HeshamMegid** [comment]
Does the same happen when you use `setSelectedSegmentIndex:animated`?
