### ISSUE TITLE
how can i alter zhe titleFont

### ISSUE THREAD

**Issue by xiJieGuYuan** [HeshamMegid/HMSegmentedControl#174]
self.segmentedControl4.sectionTitles = @[@"图文详情", @"规格参数", @"热门推荐"];
 how can i change sectionTitles textFont  ??? 
thank you !

**Comment by nishantanthwal** [comment]
Try setting the custom font and size like this:

>     _segmentedControl.titleTextAttributes = @{NSFontAttributeName : [UIFont systemFontOfSize:16],
>                                               NSForegroundColorAttributeName : [UIColor redColor]};

It supports advanced title styling with text attributes for font, color, kerning, shadow, etc.

**Comment by HeshamMegid** [comment]
Exactly as @nishantanthwal said.
