### ISSUE TITLE
Using from storyboard...won't show up

### ISSUE THREAD

**Issue by drewpitchford** [HeshamMegid/HMSegmentedControl#176]
I've got everything the way I want it. It works perfectly except that on first load of a VC, the segment control is blank. If I tap on it, the buttons show up and everything is fine after that. Any ideas as to what to do here?

**Comment by HeshamMegid** [comment]
Have you been able to solve that issue? I'm closing this for now since it's very old. Feel free to reopen if you still have that issue.
