### ISSUE TITLE
Horizontal Scrolling.

### ISSUE THREAD

**Issue by dkeso611** [HeshamMegid/HMSegmentedControl#183]
I tried to disable horizontal scrolling by setting `userDraggable` to `NO` , but its still dragging. Any way to override this? I even tried disabling it in your code by setting it to `NO` as the default. Your help would be greatly appreciated, as my app has use of swiping left and right.

Thanks.

**Comment by HeshamMegid** [comment]
I'm unable to reproduce that issue. Can you please share the code you use to configure the control?
