### ISSUE TITLE
How to Connect HMSegmentedControl to my segmented Controller?

### ISSUE THREAD

**Issue by mangireddy58** [HeshamMegid/HMSegmentedControl#184]
I created Segment controller through story and created property as "segment".
my problem is when i am using my segment in your code getting errors.

![screen shot 2016-03-17 at 5 16 06 pm](https://cloud.githubusercontent.com/assets/14342272/13845154/13306286-ec64-11e5-9f0d-481d81392d83.png)
Error's
like this

![screen shot 2016-03-17 at 5 20 19 pm](https://cloud.githubusercontent.com/assets/14342272/13845244/a916083c-ec64-11e5-912c-3e3b784cd482.png)

**Comment by HeshamMegid** [comment]
Seems like the object type in the storyboard is set to `UISegmentedControl` rather than `HMSegmentedControl`.
