### ISSUE TITLE
Segmented not scroll to selected tab

### ISSUE THREAD

**Issue by cbarbera80** [HeshamMegid/HMSegmentedControl#193]
Hi,

I've a HMSegmentedControl with 40 tabs. If I select an element not currently visible in screen (like  [self.tab setSelectedSegmentIndex:10  animated:YES];)

the layer not move to selected tab. Could you help me please?

**Comment by QuyetND** [comment]
@:cbarbera80 I have same problem. I fix by add     [self scrollToSelectedSegmentIndex:YES]; in end of 
- (void)drawRect:(CGRect)rect {
....................
[self scrollToSelectedSegmentIndex:YES];
}

**Comment by Allui** [comment]
//This helped me
dispatch_async(dispatch_get_main_queue(), ^{
        [wekSelf.control setSelectedSegmentIndex:10 animated:YES];
});

**Comment by HeshamMegid** [comment]
@cbarbera80 can you please share the code you use to configure the control?

**Comment by dntzee** [comment]
I have same problem in swift3.0

use gcd does not work too

```swift
DispatchQueue.main.async(execute: {
            self.segmentedControl.setSelectedSegmentIndex(0, animated: false)
        })
```
