### ISSUE TITLE
Add notification badge in HMSegmentedcontrol

### ISSUE THREAD

**Issue by StephyJosePiserve** [HeshamMegid/HMSegmentedControl#194]
How can I add badge in HMSegmentedcontrol?Please help me.

**Comment by qmkCamel** [comment]
I met the same question. But the CATextLayer may not support the image. So I change the source code to add badge in  '' - (void)drawRect:(CGRect)rect '' method. I change the CATextLayer to a simple UILabel , and you can set the label`s attributedText.
![image](https://cloud.githubusercontent.com/assets/5952752/14844695/d8e8f136-0c8b-11e6-8ce6-cf8ac87d3c39.png)

**Comment by dwjdwj1216** [comment]
it helps me.Thank you.

**Comment by HeshamMegid** [comment]
That's currently not supported. Feel free to create a pull request to add that though.

**Comment by rahulvyas** [comment]
@qmkCamel Can you guide me in right approach to add badge into Segmented Control ?

**Comment by rahulvyas** [comment]
@qmkCamel Can you guide me in right approach to add badge into Segmented Control ?

**Comment by sameerkupkar** [comment]
@HeshamMegid  I am using HMSegmentedControl pod to show image i successfully add but now i need add  Badge value on top f image please heple me.
