### ISSUE TITLE
Set image size (width & height) 

### ISSUE THREAD

**Issue by andrealufino** [HeshamMegid/HMSegmentedControl#200]
I need to set image size of a single "button" in the segmented control, but don't know how to do it. I want the image fill the button space. I'm using the last version on the cocoapods in Objective-C and I'm using the style with image + text

**Comment by susuyan** [comment]
hi, @andrealufino did you find any solution? i met too

**Comment by andrealufino** [comment]
@susuyan unfortunately not

**Comment by HeshamMegid** [comment]
That's currently not possible. Feel free to create a pull request for that though.
