### ISSUE TITLE
Have you consider reusable  approach for scrollview ?

### ISSUE THREAD

**Issue by Ram-OAB** [HeshamMegid/HMSegmentedControl#205]
Hi,

I have one question here. Are you reusing the scrollview images like **Tableview**?  if not , don't you think the memory problem will arise.Please clear me here because i'm gonna use this where I need to add no. of images dynamically from remote server.

**Comment by HeshamMegid** [comment]
The control does not implement a reuse mechanism in a fashion similar to a `UITableView`, mainly because of the assumption that it's unlikely to be used with a big number of segments.
