### ISSUE TITLE
selectionIndicatorEdgeInsets bottom error

### ISSUE THREAD

**Issue by yehuawei** [HeshamMegid/HMSegmentedControl#212]
if (self.selectionIndicatorLocation == HMSegmentedControlSelectionIndicatorLocationDown) {
        indicatorYOffset = self.bounds.size.height - self.selectionIndicatorHeight + self.selectionIndicatorEdgeInsets.bottom;
    }

should be:
if (self.selectionIndicatorLocation == HMSegmentedControlSelectionIndicatorLocationDown) {
        indicatorYOffset = self.bounds.size.height - self.selectionIndicatorHeight - self.selectionIndicatorEdgeInsets.bottom;
    }

,add The height of verticalDivider is not right.

**Comment by HeshamMegid** [comment]
Thanks for reporting that. Would you mind creating a pull request?
