### ISSUE TITLE
selected color

### ISSUE THREAD

**Issue by pingcoco** [HeshamMegid/HMSegmentedControl#213]
How to add color selected above, but not underscore that, to fill the entire background

**Comment by yforyouhk** [comment]
Yes, same, cannot edit the color of the selected one

**Comment by hoikin** [comment]
Same here

**Comment by sina-kh** [comment]
Try to use:

    _segmentedControl.selectedTitleTextAttributes   = @{NSFontAttributeName : [UIFont fontWithName:fontName size:14],
                                              NSForegroundColorAttributeName : [UIColor grayColor]};

**Comment by HeshamMegid** [comment]
Use `selectedTitleTextAttributes` just like @sina-kh mentioned.

**Comment by bksasuke** [comment]
it does not change the select cell background. Also the selectionIndicatorColor can be custom, but it mixed with the segment background and show a unwanted color.
![screen shot 2016-12-02 at 4 18 51 pm](https://cloud.githubusercontent.com/assets/14750506/20828636/1428bff8-b8ab-11e6-9adf-6946dc5752c3.png)
here is my code, which desire a red color but it show a brown color instead.

elf.segmentedControl4.backgroundColor = [UIColor blackColor];
    self.segmentedControl4.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor]};
    self.segmentedControl4.selectedTitleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor]};
    self.segmentedControl4.selectionIndicatorColor = [UIColor redColor];
    self.segmentedControl4.selectionStyle = HMSegmentedControlSelectionStyleBox;
    self.segmentedControl4.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationNone;
    [self.segmentedControl4 setSelectionLayerColor:[UIColor redColor]];

**Comment by ompagi** [comment]
@bksasuke did you check `selectionIndicatorBoxOpacity` property ?
