### ISSUE TITLE
When I scroll vertically the tab highlighter always changes to 0.

### ISSUE THREAD

**Issue by Balasnest** [HeshamMegid/HMSegmentedControl#214]
I have added tableview in one of the segment View. When I am on the current section and I scroll up or down, I noticed that the tab highlighter always changes to 0. Why is it happening? scrollView.contentOffset x and y getting as 0.

This is my scrollView code:

-(void)scrollViewDidScroll:(UIScrollView *)scrollView
{
    CGFloat pageWidth = scrollView.frame.size.width;
    int page = scrollView.contentOffset.x / pageWidth;
    [self.chatSegment setSelectedSegmentIndex:page animated:YES];
    NSLog(@"scrollViewDidScroll - You are now on page %i",page);
}

**Comment by SambitPrakash** [comment]
I am also facing same problem. Please suggest how to solve from this problem.

**Comment by rabehssera** [comment]
Check which scrollview is scrolling.

-(void)scrollViewDidScroll:(UIScrollView *)scrollView
{
if ([scrollView isEqual:self.scrollView]){
   CGFloat pageWidth = scrollView.frame.size.width;
   int page = scrollView.contentOffset.x / pageWidth;
   [self.chatSegment setSelectedSegmentIndex:page animated:YES];
   NSLog(@"scrollViewDidScroll - You are now on page %i",page);
}
}

Hope that helps

**Comment by SambitPrakash** [comment]
Hello @rabehssera. Thanks for the response. Yes, it worked. Now, there is no issue
