### ISSUE TITLE
Vertical Scroll issue

### ISSUE THREAD

**Issue by Balasnest** [HeshamMegid/HMSegmentedControl#216]
I have 3 segment control. Each view has tableview on it. whenever I scroll up and down, my tab highlighter that is selected segmentrol page is changed to first segment control. How can i detect in scrollview?

**Comment by HeshamMegid** [comment]
This is related to table view cells reuse. You basically need to reconfigure the control whenever a table view cell is reused. I recommend you read a bit more about table views cell reuse.
