### ISSUE TITLE
Title and detail

### ISSUE THREAD

**Issue by rabehssera** [HeshamMegid/HMSegmentedControl#217]
Hi

I wanted to know if there was a possibility to show 2 lines of text. First line would be the section title and, under it, a section "detail". For example, the title would be "Friends" and, under it, the number of friends ?

Thanks

**Comment by HeshamMegid** [comment]
Theoretically, you should be able to do that with attributed strings, but I'm not sure if it would work as expected. Give it a try and let me know. 🙂

**Comment by zhouleiyinping** [comment]
嗨，你好，更新iOS10之后发现一个问题，CATextLayer不能正确的显示title，可以考虑使用UILabel来显示title

**Comment by DeftMKJ** [comment]
我已经换了一个了，就等作者修复了，不行的话就换掉了

**Comment by zhouleiyinping** [comment]
作者已经修复了，可以正常使用了

**Comment by rabewu** [comment]
@DeftMKJ   download v1.5.3

**Comment by zhouzhuhao** [comment]
iOS10 标题 显示不了  修复了吗？

**Comment by songhailiang** [comment]
最新的1.5.3版本已经解决

**Comment by rabehssera** [comment]
Well, I have a title and a subtitle, but now, I can't get a selected/unselected version...
