### ISSUE TITLE
fontSize Smaller than 18.0f then cannot visible

### ISSUE THREAD

**Issue by MachineVk** [HeshamMegid/HMSegmentedControl#218]
segmentedControl = [[HMSegmentedControl alloc] initWithSectionTitles:@[@"推荐", @"分类", @"成长" ,@"榜单",@"社区"]];
    segmentedControl.frame = CGRectMake(0, 0, SCREEN_WIDTH, 45);
    
    
    segmentedControl.titleTextAttributes = @{NSForegroundColorAttributeName:COLORFROMRGB(0x69696b),//
                                             NSFontAttributeName:[UIFont systemFontOfSize:18.0f],
                                             };
    
    
    segmentedControl.selectedTitleTextAttributes = @{NSForegroundColorAttributeName:COLORFROMRGB(0xfe7547)};
    segmentedControl.selectionIndicatorColor = COLORFROMRGB(0xfe7547) ;
    segmentedControl.selectionStyle = HMSegmentedControlSelectionStyleTextWidthStripe;
    segmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationDown;
    segmentedControl.selectionIndicatorHeight = 1.5 ;
    segmentedControl.selectionIndicatorEdgeInsets = UIEdgeInsetsMake(0, -10, 0, -20);

  when fontSize is smaller than 18.0f ,i cannot see anything (ios 10).   i don’t know what’s happened .Could you help me ?

**Comment by HeshamMegid** [comment]
Please try that on the [latest release](https://github.com/HeshamMegid/HMSegmentedControl/releases/tag/v1.5.3) and let me know if the problem still exists.
