### ISSUE TITLE
sectionTitles  not show  on iOS 10

### ISSUE THREAD

**Issue by hhfa** [HeshamMegid/HMSegmentedControl#219]
sectionTitles  not show  on iOS 10

**Comment by bingbingBang** [comment]
same issue with #215

**Comment by Leon-OS** [comment]
iOS10：one or two words is not show，but sectionTitles words number than three, is show normal.
quickly: add ' ' at word head and foot. "ok" --> " ok "

**Comment by ricsantos** [comment]
This is a duplicate of #215

**Comment by HeshamMegid** [comment]
This has been fixed in the latest version. Please check it out.
