### ISSUE TITLE
Why is it still 1.5.2 version in cocoapods?

### ISSUE THREAD

**Issue by songhailiang** [HeshamMegid/HMSegmentedControl#220]
I find the podspec file had been updated, but when I search in cocoapods, it is still 1.5.2. 
So, what‘s wrong?

**Comment by ricsantos** [comment]
It looks like the commit was incorrectly tagged `1.5.3` instead of `v1.5.3` as expected by the Podfile.

**Comment by ricsantos** [comment]
As mentioned in [this comment](https://github.com/HeshamMegid/HMSegmentedControl/issues/215#issuecomment-246540943) for issue #215, in the meantime use this in your Podfile as a workaround:

    pod 'HMSegmentedControl', :git =>'https://github.com/HeshamMegid/HMSegmentedControl.git', :tag => '1.5.3'

**Comment by HeshamMegid** [comment]
I have just pushed 1.5.3 to Cocoapods and fixed the tag. You should be able to see it now.

**Comment by goodstechinc** [comment]
I'm still met with an error. 

None of your spec sources contain a spec satisfying the dependency: `HMSegmentedControl (~> 1.5.3)`.
