### ISSUE TITLE
sectionsTitle still can't show when the system is up ios 10.0 ,as the ststem is ios 10.0.1

### ISSUE THREAD

**Issue by heiseyoumosjm** [HeshamMegid/HMSegmentedControl#221]
sectionsTitle still can't show when the system is up ios 10.0 ,as the ststem is ios 10.0.1

**Comment by damthieuquang** [comment]
@HeshamMegid 
SegmentedController works well with iOS 9 and lower but in iOS 10 it has a problem
![screen shot 2016-09-15 at 9 31 31 am](https://cloud.githubusercontent.com/assets/6957056/18536437/88f9b4de-7b27-11e6-8ab4-36b8cdb645c6.png)

**Comment by ricsantos** [comment]
This is a duplicate of #215

**Comment by HeshamMegid** [comment]
This issue has been fixed. Please update to the latest release.
