### ISSUE TITLE
Some titles are invisible on iOS 10

### ISSUE THREAD

**Issue by rabewu** [HeshamMegid/HMSegmentedControl#222]
Some CATextLayer will disappear on iOS 10. Anyone had same issue ?

**Comment by zhhlmr** [comment]
Got the same problem here.Anyone knows ?

**Comment by XZYsunny** [comment]
Got the same problem here.Anyone knows ?

**Comment by XZYsunny** [comment]
please user 1.5.3

**Comment by fel835** [comment]
cocoapod can not use 1.5.3,can only use 1.5.2

**Comment by dingchuandong** [comment]
update 1.5.3 this problem has save

**Comment by rabewu** [comment]
Thx all! Version 1.5.3 fixed this problem!

**Comment by alienallen** [comment]
Got the sample problem, upgrade to 1.5.3 fixed it. Million thanks!

**Comment by light-bo** [comment]
Thx all! Version 1.5.3 fixed this problem ^_^

**Comment by mickeyl** [comment]
Thanks for the update. This issue can be closed.
