### ISSUE TITLE
initWithSectionTitles call [self initWithFrame]

### ISSUE THREAD

**Issue by cwilhelm** [HeshamMegid/HMSegmentedControl#231]
When comparing initWithSectionTitles and initWithSectionImages, you see that initWithSectionTitles calls `[self initWithFrames]`, whereas initWithSectionImages calls `[super initWithFrames]`. Probably both methods should call `[super initWithFrames]`.

**Comment by HeshamMegid** [comment]
I've merged #232 which fixes this. Thanks for reporting and creating the pull request!
