### ISSUE TITLE
Error: [_SwiftValue pointSize]: unrecognized selector sent to instance xxxx 

### ISSUE THREAD

**Issue by monica18p** [HeshamMegid/HMSegmentedControl#234]
I upgraded to xcode 8, swift3. After migration i am getting following 
`[_SwiftValue pointSize]: unrecognized selector sent to instance 0x6000006562c0`
at  
<img width="957" alt="screen shot 2016-10-04 at 12 31 48 pm" src="https://cloud.githubusercontent.com/assets/6171473/19064993/97cc060e-8a2e-11e6-8961-ebfd4ca403d1.png">

Please tell me the workaround for this. 
By the way the library has been too helpful to me till now. Great work.!

**Comment by daviwiki** [comment]
Hi Monica, 

I found the same problem with a code like this:
let appearance = UINavigationBar.appearance()
        let font = UIFont(name: "SFUIText-Regular", size: 18)
        appearance.titleTextAttributes = [
            NSFontAttributeName : font
        ]

and I solve remove the conditional clause to the font with this way:
        let font = UIFont(name: "SFUIText-Regular", size: 18)**!**

Actually i don't know the reason for this crash but i solve using this. I hope to be helpful.
Best regards.

**Comment by HeshamMegid** [comment]
@monica18p are you using the control with a custom font?

**Comment by monica18p** [comment]
@HeshamMegid Yes i have used custom font

@daviwiki I haven't used your work around. Will let you know whether it worked for me or not. Thnx

**Comment by HeshamMegid** [comment]
@monica18p I believe you need to unwrap your custom font, like @daviwiki suggested.
