### ISSUE TITLE
Last Section title disappeared on iOS 10

### ISSUE THREAD

**Issue by osolano** [HeshamMegid/HMSegmentedControl#245]
Since the upgrade from iOS 9 to iOS 10 I've noticed a bunch of different issues on apps I am working on. 
In this case, I an app that I use HMSegmentedControl for two different views has the last sectionTitle disappeared.

I also looked through some of the issues, and did the pod update to 1.5.3 but still the issue persists...

3 Section Titles, last one missing
![image](https://cloud.githubusercontent.com/assets/280426/20015885/72e165aa-a27a-11e6-9d7b-8962731b8647.png)

2 Section Titles, last one missing
![image](https://cloud.githubusercontent.com/assets/280426/20015900/82f6aebe-a27a-11e6-8268-c254c3aaa2bd.png)

These are displayed on a UIViewController... here is a snippet

```
-(void)initializeTopControl {
    self.typeSegmentedControl = [[HMSegmentedControl alloc] initWithSectionTitles:@[@"Blood\nPressure", @"Heart Rate", @"BMI"]];
    self.typeSegmentedControl.frame = CGRectMake(0, 0, self.view.frame.size.width, 70);
	self.typeSegmentedControl.backgroundColor = [UIColor flatSkyBlueColor];
	self.typeSegmentedControl.selectedSegmentIndex = 0;
	self.typeSegmentedControl.titleTextAttributes = @{NSForegroundColorAttributeName : [[UIColor whiteColor] colorWithAlphaComponent:0.4],NSFontAttributeName:[UIFont systemFontOfSize:16]};
	
	self.typeSegmentedControl.selectedTitleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor]};
	
	self.typeSegmentedControl.selectionIndicatorColor = [UIColor whiteColor];
	self.typeSegmentedControl.userDraggable = NO;
	self.typeSegmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationDown;
	self.typeSegmentedControl.selectionStyle = HMSegmentedControlSelectionStyleTextWidthStripe;
	self.typeSegmentedControl.tag = 3;
	self.typeSegmentedControl.shouldAnimateUserSelection = NO;

	[self.view addSubview:self.typeSegmentedControl];
}
```

**Comment by HeshamMegid** [comment]
It's showing up fine here.

![simulator screen shot nov 6 2016 12 34 07 pm](https://cloud.githubusercontent.com/assets/1529229/20036877/67ced61c-a41d-11e6-9b23-ee7a0946383e.png)

Do you have any extra details that would help reproduce this?

**Comment by kansaragaurav** [comment]
i have four section and can't see the last section text , and i also try to add fifth one than i can't display section text for both (4 & 5).

**Comment by kansaragaurav** [comment]
hi @osolano  use update library for solve this issue
