### ISSUE TITLE
Non initialization, modify the value of the title, As follows: but it cleared the previous property settings

### ISSUE THREAD

**Issue by EarthMass** [HeshamMegid/HMSegmentedControl#248]
Non initialization, modify the value of the title,
As follows: but it cleared the previous property settings

//    //修改标题
    [segmentedControl  setTitleFormatter:^NSAttributedString *(HMSegmentedControl *segmentedControl1, NSString *title, NSUInteger index, BOOL selected) {
        
        segmentedControl1.titleTextAttributes = @{NSForegroundColorAttributeName : BlackFontColor,NSFontAttributeName : TitleFont};
        segmentedControl1.selectedTitleTextAttributes = @{NSForegroundColorAttributeName : BlueLightColor,NSFontAttributeName : TitleFont};

        
        if (index == 0) {
            title = @"1212（212）";
        }
        NSAttributedString * titleStr = [[NSAttributedString alloc] initWithString:title attributes:@{NSFontAttributeName : TitleFont}];
        return titleStr;
    }];

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
