### ISSUE TITLE
when title less  than 3 words  set the font of the title  all titles missing

### ISSUE THREAD

**Issue by lp380490944** [HeshamMegid/HMSegmentedControl#251]

**Comment by yanglk** [comment]
I met the same problem.

**Comment by lazzynan** [comment]
I met the same problem，when the words width is not long enough, I find this is a bug of CATextLayer, I did't find any good solution and just add more space

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
