### ISSUE TITLE
textType and  HMSegmentedControlSegmentWidthStyleDynamic  crash when sectionTitles count equal zero

### ISSUE THREAD

**Issue by lilin87788** [HeshamMegid/HMSegmentedControl#252]
![994e3c97-4cbf-45a2-8a98-5e1879850253](https://cloud.githubusercontent.com/assets/1483811/21225668/dff00cf2-c30c-11e6-9c22-f967deba817d.png)

two condition to show this crash
self.segmentWidthStyle = HMSegmentedControlSegmentWidthStyleDynamic;
self.sectionTitles = array with count 0;

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
