### ISSUE TITLE
why don't declare ‘setSelectedSegmentIndex:(NSUInteger)animated:(BOOL)notify:(BOOL)’ in interface?

### ISSUE THREAD

**Issue by MrKang** [HeshamMegid/HMSegmentedControl#256]
I tried to change selectedSegmentIndex manually and the 'UIControlEventValueChanged' event didn't be triggered. Then I found  ‘setSelectedSegmentIndex:(NSUInteger)animated:(BOOL)notify:(BOOL)’ in HMSegmentedControl.m.Why don't make ‘setSelectedSegmentIndex:(NSUInteger)animated:(BOOL)notify:(BOOL)’  public?

**Comment by Polant** [comment]
I found the same problem. Maybe it will be better if 'setSelectedSegmentIndex:(NSUInteger)animated:(BOOL)notify:(BOOL)' declared in header file.

**Comment by HeshamMegid** [comment]
You should be able to do that by setting the `selectedSegmentIndex` property.
