### ISSUE TITLE
Right to left orientation

### ISSUE THREAD

**Issue by rabehssera** [HeshamMegid/HMSegmentedControl#259]
Hi

It seems like the component doesn't go from right to left if the language is Hebrew or Arabic.

Any solution for that ?

**Comment by selaysoysal** [comment]
Hi @rabehssera  have ever solved your problem? If you solved can you explain how?

**Comment by Abdul-Hannan** [comment]
I was able to workaround by reversing my Array and selecting the last index instead of first in RTL Language

**Comment by MahmoudAbunaji** [comment]
Any update on the issue , Iam try to reverse the array and also setSelectedIndex the last index of my array but still stuck on moving  the indicator to the last item in the segment it's already supported in Obj.C by using scroll method but in swift it's not any help ?

**Comment by HeshamMegid** [comment]
This is currently not supported. Feel free to open a pull request if you'd like to implement it.
