### ISSUE TITLE
It dosen't scroll when i turn fullscreen back

### ISSUE THREAD

**Issue by Shin1122** [HeshamMegid/HMSegmentedControl#262]
视图切换至横屏,再切换回竖屏后,segment选项失灵,只能滑动,请问如何解决?
In the project, the view switch to the horizontal screen, and then switch back to the vertical screen, click on segment options the scrollview scrolls fail, can only slide on scrollview, how to solve?

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
