### ISSUE TITLE
Custom view as a segment

### ISSUE THREAD

**Issue by RishabhTayal** [HeshamMegid/HMSegmentedControl#263]
Add an ability to specify a custom view as a segment.

**Comment by ClegeJJ** [comment]
That makes two of us.

**Comment by AlexHedley** [comment]
👍🏻

**Comment by ignasibm** [comment]
Let's make it three!

**Comment by Rommanski** [comment]
I'll continue, four!

**Comment by HeshamMegid** [comment]
This is currently not possible. Please feel free to open a PR if you'd like to implement it.
