### ISSUE TITLE
Indicator width is incorrect when use selectionIndicatorEdgeInsets property

### ISSUE THREAD

**Issue by smellflower** [HeshamMegid/HMSegmentedControl#267]
controlSegmented_.segmentWidthStyle = HMSegmentedControlSegmentWidthStyleDynamic;

    controlSegmented_.selectionStyle = HMSegmentedControlSelectionStyleTextWidthStripe;

    controlSegmented_.segmentEdgeInset = UIEdgeInsetsMake(0, 15, 0, 15);

    controlSegmented_.selectionIndicatorEdgeInsets = UIEdgeInsetsMake(0, 15, 0, 15);

when i set the same segmentEdgeInset and selectionIndicatorEdgeInsets, but i got this style 

![image](https://cloud.githubusercontent.com/assets/1149610/22617027/7c886266-eaf5-11e6-88c0-e09fa2e9dc7d.png)

the indicator is longer than the text. Then i checked ur code, i found u only minus the right of edges of indicator width,  i think u should minus left and right of edges of indicator width. Please fix it ? Thks.

![image](https://cloud.githubusercontent.com/assets/1149610/22617048/0e87850c-eaf6-11e6-95bb-5d50dd88b5ac.png)

**Comment by arietis** [comment]
@smellflower Could you please test the pull request above?

**Comment by HeshamMegid** [comment]
This has been fixed in the latest version.
