### ISSUE TITLE
how to set titles from let to right ,not always center?

### ISSUE THREAD

**Issue by bianxiang** [HeshamMegid/HMSegmentedControl#270]
when titles count are too short how to set titles from left to right ,not always center?

**Comment by CoderYLZhang** [comment]
I have the same problem

**Comment by ludovico87** [comment]
some problem here

**Comment by Melomat** [comment]
segmentedControl.segmentWidthStyle = .dynamic

**Comment by HeshamMegid** [comment]
@Melomat's suggestion should work for this.
