### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Pinwheeler** [HeshamMegid/HMSegmentedControl#273]
Could we get some accessibility by default on the titles? Would be useful for UI testing

**Comment by j796160836** [comment]
Hi Pinwheeler, 
I encounter the same problem as you. I add some buttons to support this feature.
You can check it and gave me some comments, thanks.

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
