### ISSUE TITLE
Titles not "swipable" but "tappable"

### ISSUE THREAD

**Issue by graewer** [HeshamMegid/HMSegmentedControl#275]
How can i change the functionality the way the user not has to swipe to next section but simply can tap it?

Thanks  a lot!

**Comment by HeshamMegid** [comment]
Not sure I understand. Can you explain more?

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
