### ISSUE TITLE
How to use in vertical Mode

### ISSUE THREAD

**Issue by Narendra1098** [HeshamMegid/HMSegmentedControl#278]
I have to need HMSegmentedControl in vertical mode. Is it possible?
![screen shot 2017-03-27 at 8 20 29 pm](https://cloud.githubusercontent.com/assets/3763167/24362590/dec82c7e-132a-11e7-884e-959e07c0738c.png)

**Comment by HeshamMegid** [comment]
Nope, currently not supported.
