### ISSUE TITLE
Xcode 8.3 update throws warnings

### ISSUE THREAD

**Issue by gateway** [HeshamMegid/HMSegmentedControl#280]
Just a fyi for Xcode 8.3 users, you will see warnings.. we just updated today (we are pulling this framework though the pod file)

![image](https://cloud.githubusercontent.com/assets/519563/24726822/910616ba-1a08-11e7-9c3f-2932a4a14ee1.png)

**Comment by SrikanthKabadi** [comment]
There is a fix already in the source code but it is not released. When can we expect this release? @HeshamMegid

**Comment by ranhsd** [comment]
Hi, Anybody is planning to create a release out of it ? 

thanks.
