### ISSUE TITLE
Example of HMSegmentedControlTypeTextImages

### ISSUE THREAD

**Issue by AlexHedley** [HeshamMegid/HMSegmentedControl#284]
Is there an example of showing Text and Images within the control?

Use `[[HMSegmentedControl alloc] initWithSectionImages:images sectionSelectedImages:selectedImages titlesForSections:titles];`

I've tried adding the following to [ViewController.m](https://github.com/HeshamMegid/HMSegmentedControl/blob/master/HMSegmentedControlExample/ViewController.m)

```objc
NSArray<NSString *> *titles = @[@"One", @"Two", @"Three", @"Four"];
    
HMSegmentedControl *segmentedControl5 = [[HMSegmentedControl alloc] initWithSectionImages:images sectionSelectedImages:selectedImages titlesForSections:titles];
segmentedControl5.frame = CGRectMake(0, 480, viewWidth, 120);
segmentedControl5.selectionIndicatorHeight = 4.0f;
segmentedControl5.backgroundColor = [UIColor clearColor];
segmentedControl5.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationDown;
segmentedControl5.selectionStyle = HMSegmentedControlSelectionStyleTextWidthStripe;
[segmentedControl5 addTarget:self action:@selector(segmentedControlChangedValue:) forControlEvents:UIControlEventValueChanged];
[self.view addSubview:segmentedControl5];
```

<img src="https://cloud.githubusercontent.com/assets/1573469/26209118/d7fb4818-3be3-11e7-8b89-18e863f38043.png" width= "300" alt="hmsegmentedcontroltypetextimages" />

---

I'd like to implement something like
![segmentedcontrol](https://cloud.githubusercontent.com/assets/1573469/26208968/5d3aaea2-3be3-11e7-9a16-edc6e5cbd456.png)

Issue https://github.com/HeshamMegid/HMSegmentedControl/issues/263 might be an alternative.

**Comment by AlexHedley** [comment]
Asked on SO too. (https://stackoverflow.com/questions/44569864/round-top-corners-of-selected-hmsegmentedcontrol-item)

**Comment by HeshamMegid** [comment]
This is currently not supported.
