### ISSUE TITLE
Change Font

### ISSUE THREAD

**Issue by imuhammadjabbar** [HeshamMegid/HMSegmentedControl#288]
is there a way to change the font?

**Comment by pvcary** [comment]
I also have the same question ^

**Comment by Sebacho-Barajas** [comment]
this is how I changed the font.
```
 [_segmentedControl setTitleFormatter:^NSAttributedString *(HMSegmentedControl *segmentedControl, NSString *title, NSUInteger index, BOOL selected) {
        NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:[title uppercaseString]];
        UIFont *font = [UIFont fontWithName:@"Your Font" size:13];
        [attributedString addAttribute:NSFontAttributeName value:font range:NSMakeRange(0, [attributedString length])];
        [attributedString addAttribute:NSForegroundColorAttributeName value:[UIColor whiteColor] range:NSMakeRange(0, [attributedString length])];
        return attributedString;
    }];

```

**Comment by Yongheng1992** [comment]
> 这就是我改变字体的方式。
> 
> ```
>  [_segmentedControl setTitleFormatter:^NSAttributedString *(HMSegmentedControl *segmentedControl, NSString *title, NSUInteger index, BOOL selected) {
>         NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:[title uppercaseString]];
>         UIFont *font = [UIFont fontWithName:@"Your Font" size:13];
>         [attributedString addAttribute:NSFontAttributeName value:font range:NSMakeRange(0, [attributedString length])];
>         [attributedString addAttribute:NSForegroundColorAttributeName value:[UIColor whiteColor] range:NSMakeRange(0, [attributedString length])];
>         return attributedString;
>     }];
> ```
How to modify the selected font

**Comment by HeshamMegid** [comment]
As @Sebacho-Barajas mentioned, you should do that using attributed strings.
