### ISSUE TITLE
How to disable selection of particular segment index.

### ISSUE THREAD

**Issue by amittiwaribit** [HeshamMegid/HMSegmentedControl#290]
I have 4 segment item, in which for some condition I do not want to select the first segment index. 
for example UISegment controller have API [segmentedControl setEnabled:NO forSegmentAtIndex:0];

Hence the corresponding API is missing in HMSegmentedControl.
Please help to resolve this issue.

**Comment by ShaoJenChen** [comment]
I have the same issue.

**Comment by ShaoJenChen** [comment]
I forked this ,and add a setEnabled:forSegmentAtIndex function
i hope this helps

**Comment by amittiwaribit** [comment]
thanks for your help but setEnabled:forSegmentAtIndex is API of UISegmentControl. HMSegmentedControl does not have any API to disable any segment control index button.

**Comment by ShaoJenChen** [comment]
I add setEnabled:forSegmentAtIndex to HMSegmentedControl in my repository as below.
and send a pull request to it.
https://github.com/ShaoJenChen/HMSegmentedControl/commit/02bc4276f12cc8a885c0b6c3ace41d3aff273be0

**Comment by HeshamMegid** [comment]
@amittiwaribit this is currently not possible.
