### ISSUE TITLE
Bug in IndicatorLocation

### ISSUE THREAD

**Issue by hahalalamummy** [HeshamMegid/HMSegmentedControl#291]
#![screen shot 2017-06-16 at 5 19 26 pm](https://user-images.githubusercontent.com/21301002/27222833-16a8f71e-52b8-11e7-8a15-f42128cf909a.png)
`<br>    func setupViewTabCollection() {

        let segmentedControl: HMSegmentedControl = HMSegmentedControl(sectionTitles: ["ALL MANGA", "POPULAR", "NEW MANGA", "LAST UPDATE"])
        segmentedControl.frame = CGRect(x: 0, y: 0, width: viewTabCollection.frame.width, height: viewTabCollection.frame.height)
        segmentedControl.addTarget(self, action: #selector(self.segmentedControlChangedValue), for: .valueChanged)
        segmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocation(rawValue: 1)!
        viewTabCollection.addSubview(segmentedControl)
    }
    
    func segmentedControlChangedValue() {
        
    }`
It's normally (no bug) when I set HMSegmentedControlSelectionIndicatorLocation into up.
But when I change to down, it show 2 selection indicator: 1 normal, 1 stay still on screen.

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
