### ISSUE TITLE
ChangeText or Image Position - HMSegmentedControlTypeTextImages

### ISSUE THREAD

**Issue by syedrazackimran** [HeshamMegid/HMSegmentedControl#292]
<img width="374" alt="screen shot 2017-06-18 at 10 00 52 pm" src="https://user-images.githubusercontent.com/15051045/27261658-b3e7bd48-5471-11e7-8713-56c3e135f497.png">
Hi,
 i need to change text position x axis . top image which i attached that is issues .. i don't know how to fix that one. i attached image below i need similar like this .. kindly check it once and update me . thanks 

<img width="414" alt="screen shot 2017-06-18 at 10 02 38 pm" src="https://user-images.githubusercontent.com/15051045/27261678-12bd289e-5472-11e7-8c5c-3e4054b38747.png">

**Comment by sara-shokry** [comment]
did you find any solution?

**Comment by ramunasjurgilas** [comment]
@syedrazackimran Dod you found solution?

**Comment by rahulvyas** [comment]
I am also looking for solution did you find any solution ?
I am looking for Image Then text. Image with each label.

**Comment by HeshamMegid** [comment]
Please check `HMSegmentedControlImagePosition`.
