### ISSUE TITLE
Is it possible to reduce the widget of the active option background view?

### ISSUE THREAD

**Issue by prakashraman** [HeshamMegid/HMSegmentedControl#293]
Is it possible to reduce the widget of the active option background view?

I am basically trying to create the following.

<img width="609" alt="segment-control" src="https://user-images.githubusercontent.com/36934/27648594-b19b6390-5c4c-11e7-9ee4-3b8445006503.png">

Is this possible using the library?

**Comment by HeshamMegid** [comment]
This is currently not possible. Please feel free to open a PR if you'd like to implement it.
