### ISSUE TITLE
the layer.cornerRadius was clip

### ISSUE THREAD

**Issue by NXZXing** [HeshamMegid/HMSegmentedControl#295]
hello,when i use it ,i have a problem.the layerCorner is clip,such as the picture.
![image](https://user-images.githubusercontent.com/13497935/28309772-0446a010-6bdd-11e7-8bbb-d25744fad310.png)

my code is such as:
![image](https://user-images.githubusercontent.com/13497935/28309910-67ab3d6e-6bdd-11e7-92f2-beee825b477d.png)

How can i do can solute it? Thanks!

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
