### ISSUE TITLE
How to set text align for each title?

### ISSUE THREAD

**Issue by MaorS** [HeshamMegid/HMSegmentedControl#296]
There is a way to set text align for each title?
For example :
![screen shot 2017-07-18 at 14 18 20](https://user-images.githubusercontent.com/20594674/28314746-697a4cde-6bc4-11e7-9bbf-99c01fd8886e.png)
Text 1 will have left align
Text 2 will have center align
Text 3 will have right align

Thanks

**Comment by selaysoysal** [comment]
Hi @MaorS have you ever solved your problem? If you solved can you explain how?

**Comment by HeshamMegid** [comment]
This is currently not possible.
