### ISSUE TITLE
Drag Cell bottom segment selectionIndicatorLocation bar with respect to scrollview

### ISSUE THREAD

**Issue by Abhishek-NickelFox** [HeshamMegid/HMSegmentedControl#297]
<img width="380" alt="screen shot 2017-08-09 at 9 38 49 am" src="https://user-images.githubusercontent.com/27338504/29104859-ad2a15f8-7ce6-11e7-81f8-f60cb74adb15.png">

As shown in snapshot i want that segment bottom selectionIndicatorLocation to be moved when scroll view is swiped right/left. How can i do that?
@HeshamMegid

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
