### ISSUE TITLE
SWIFT3 : Landscape orientation width doesnot fill the screen on any device Iphone/Ipad

### ISSUE THREAD

**Issue by ammadakhtar** [HeshamMegid/HMSegmentedControl#299]
![simulator screen shot 16-aug-2017 4 51 27 pm](https://user-images.githubusercontent.com/26001327/29361963-372aceb6-82a3-11e7-9a7e-36d5ad7ad1c3.png)
See the One Two Three 4 Five 
&
Worldwilde ........ segments

**Comment by ammadakhtar** [comment]
I did this to solve , but this should have been done in the pod automatically
` override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        if UIDevice.current.orientation.isLandscape {
            print("landscape")
            let screensize : CGRect = UIScreen.main.bounds
            let width = screensize.width
            let segmentedControl = HMSegmentedControl(sectionTitles: ["One","Two","Three", "4", "Five"])
            segmentedControl?.frame = CGRect(x: 0, y: 108, width: width, height: 60)
            segmentedControl?.backgroundColor = UIColor(red: 35/255, green: 183/255, blue: 229/255, alpha: 1.0)
            segmentedControl?.isVerticalDividerEnabled = true
            segmentedControl?.verticalDividerColor = UIColor.white
            segmentedControl?.verticalDividerWidth = CGFloat(2.0)
            segmentedControl?.selectionIndicatorColor = UIColor(red: 81/255, green: 216/255, blue: 255/255, alpha: 1.0)
            segmentedControl?.titleTextAttributes = [NSForegroundColorAttributeName: UIColor.white]
            segmentedControl?.addTarget(self, action: #selector(segmentedControlChangedValue), for: .valueChanged)
            segmentedControl?.selectionIndicatorLocation = .down
            segmentedControl?.selectionStyle = .fullWidthStripe
            view.addSubview(segmentedControl!)
        }
}`

**Comment by HeshamMegid** [comment]
Right now, this should be handled by the view that embeds the control rather than the control itself.
