### ISSUE TITLE
Rounding the top corners of the selection layer only

### ISSUE THREAD

**Issue by Axemasta** [HeshamMegid/HMSegmentedControl#306]
I want to create a custom segment control which has only rounded top corners. I've been playing about with the example demo and I have come across an interesting predicament.

The layer I want to affect is the selectionBoxLayer, I have currently tried this code:

    CAShapeLayer *maskLayer = [CAShapeLayer layer];
    maskLayer.path = [UIBezierPath bezierPathWithRoundedRect:self.bounds byRoundingCorners:UIRectCornerTopLeft | UIRectCornerTopRight cornerRadii:(CGSize){10.0, 10.0}].CGPath;
    self.selectionIndicatorBoxLayer.mask = maskLayer;

This does half of the job, it will round the top left corner, but not the top right corner. Interestingly only the left hand side corners can be rounded at all. If I change the rounding style to all corners then only the top / bottom left corners that will round (https://imgur.com/66cX0i8). Another thing to note is that when you start adding a mask into the method to create the selection layer itself the animation will be effected by the mask, although this isn't a huge concern.

What I want to know is if there is a way to either round both the top corners through masking, or whether I could round the actual rectangle that is being created?

Cheers

**Comment by jihengcong** [comment]
how can I add layer corners to the selected segment

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.

**Comment by AlexHedley** [comment]
[89](https://github.com/HeshamMegid/HMSegmentedControl/issues/89)
