### ISSUE TITLE
Cocoapod update

### ISSUE THREAD

**Issue by rabehssera** [HeshamMegid/HMSegmentedControl#307]
Hello

Can you please release a new version of the library on Cocoapods to include the image position ?

Thanks

**Comment by yangcaimu** [comment]
I added the following code in my podfile.
```ruby
pod 'HMSegmentedControl', :git => 'https://github.com/HeshamMegid/HMSegmentedControl.git', :commit => '16fad4a'
```

**Comment by HeshamMegid** [comment]
1.5.5 is on CocoaPods now.
