### ISSUE TITLE
how to set Indicator cornerRadius?

### ISSUE THREAD

**Issue by yangzheng006** [HeshamMegid/HMSegmentedControl#312]

**Comment by chenhuafeng** [comment]
@interface HMSegmentedControl ()
@property (nonatomic, strong) CALayer *selectionIndicatorStripLayer;
@end

segmentedControl.selectionIndicatorStripLayer.cornerRadius      = 1.5;
segmentedControl.selectionIndicatorStripLayer.masksToBounds = YES;

**Comment by CoderCMY** [comment]
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if let subLayers = segmentedControl.subviews.first?.layer.sublayers, let indicatorLayer = subLayers.last {
            indicatorLayer.cornerRadius = segmentedControl.selectionIndicatorHeight / 2.0
            indicatorLayer.masksToBounds = true
        }
    }

**Comment by CoderCMY** [comment]
override func viewDidAppear(_ animated: Bool) {
              super.viewDidAppear(animated)
             if let subLayers = segmentedControl.subviews.first?.layer.sublayers, let indicatorLayer = subLayers.last {
                 indicatorLayer.cornerRadius = segmentedControl.selectionIndicatorHeight / 2.0
                 indicatorLayer.masksToBounds = true
             }
}

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
