### ISSUE TITLE
Showing spaces in the segment items names!

### ISSUE THREAD

**Issue by MahmoudAbunaji** [HeshamMegid/HMSegmentedControl#313]
In my app I'm using the segment filter menu to filter the restaurant food types and in one rest. it show spaces in the item name , I think the issue the item block size is takes the long size of all the items may it's not auto. , Pls help .

<img width="325" alt="screen shot 2017-12-21 at 6 07 42 pm" src="https://user-images.githubusercontent.com/24670225/34261507-5e54a256-e67a-11e7-8bc5-e6cfe34cc637.png">
<img width="348" alt="screen shot 2017-12-21 at 6 07 27 pm" src="https://user-images.githubusercontent.com/24670225/34261508-5f23f7c2-e67a-11e7-8227-61429d0e0a8f.png">

**Comment by HeshamMegid** [comment]
This is currently not possible. Please feel free to open a PR if you'd like to implement it.
