### ISSUE TITLE
Alway showing default page index 0 how to change it by programmatically

### ISSUE THREAD

**Issue by Ashutos39** [HeshamMegid/HMSegmentedControl#315]
I am using HmSegmentcontroller for selecting products its working fine but when I am trying to change the segment which is default 0 it is changing but connected view pages are not changing properly according to that Plz help to solve this issue......

**Comment by taidypanda** [comment]
sourcecode：    [self setSelectedSegmentIndex:index animated:NO notify:NO];
change to:     [self setSelectedSegmentIndex:index animated:NO notify:YES];

**Comment by Ashutos39** [comment]
Thanks for replying, I got solution its working fine now.
