### ISSUE TITLE
unable to capture view hierarchy(xcode9.2 iOS 11)

### ISSUE THREAD

**Issue by turboxing** [HeshamMegid/HMSegmentedControl#316]
-[DBGViewDebugger updateDebugHierarchy]_block_invoke_2
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

**Comment by HeshamMegid** [comment]
This should be fixed by https://github.com/HeshamMegid/HMSegmentedControl/pull/309

Please check and let me know.
