### ISSUE TITLE
Anchor the segment control to the center, even the first and last segment.

### ISSUE THREAD

**Issue by nitish07** [HeshamMegid/HMSegmentedControl#320]
I'd like the segment control to, regardless of whether the last, first, any index is selected, it scrolls it to the center. 

I understand this would result in a lot of white space, but I'd still like the option to do so. 

Here is an example of what I mean. 

[Index 0 selected](https://imgur.com/a/CKx0J3u)
[Index 1 selected](https://imgur.com/a/1czOTBR)
[Index 2 selected](https://imgur.com/a/HtBvzgy)

Regardless of how many sections the segment has the behaviour should mimic the above.

Is this possible?

**Comment by HeshamMegid** [comment]
This is currently not possible. Please feel free to open a PR if you'd like to implement it.
