### ISSUE TITLE
when segmentWidthStyle is HMSegmentedControlSegmentWidthStyleFixed, I can't set selectionIndicatorEdgeInsets

### ISSUE THREAD

**Issue by jiangsujww** [HeshamMegid/HMSegmentedControl#322]
In [- (CGRect)frameForSelectionIndicator] method,  

CGRectMake((self.segmentWidth + self.selectionIndicatorEdgeInsets.left) * self.selectedSegmentIndex, indicatorYOffset, self.segmentWidth - self.selectionIndicatorEdgeInsets.right, self.selectionIndicatorHeight);

when I set segmentWidthStyle is HMSegmentedControlSegmentWidthStyleFixed and selectionStyle is HMSegmentedControlSelectionStyleFullWidthStripe, I can't set selectionIndicatorEdgeInsets.

I think is:

CGRectMake(self.segmentWidth * self.selectedSegmentIndex + self.selectionIndicatorEdgeInsets.left, indicatorYOffset, self.segmentWidth - self.selectionIndicatorEdgeInsets.right, self.selectionIndicatorHeight);

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
