### ISSUE TITLE
Too many CALayers were added to HMSegmentedControl after selection changed.

### ISSUE THREAD

**Issue by mrahmiao** [HeshamMegid/HMSegmentedControl#323]
My guess is that the selection change event triggered the `drawRect(_:)` method and in which the `addBackgroundAndBorderLayerWithRect(_:)` get called.

![screen shot 2018-06-13 at 4 09 35 pm](https://user-images.githubusercontent.com/1203920/41338257-33c61154-6f24-11e8-9f07-e54bb9e9aa83.png)

https://github.com/HeshamMegid/HMSegmentedControl/blob/ae84d092891b3e18d89ccc8edae10f2bb93f0d55/HMSegmentedControl/HMSegmentedControl.m#L271

https://github.com/HeshamMegid/HMSegmentedControl/blob/ae84d092891b3e18d89ccc8edae10f2bb93f0d55/HMSegmentedControl/HMSegmentedControl.m#L348

https://github.com/HeshamMegid/HMSegmentedControl/blob/ae84d092891b3e18d89ccc8edae10f2bb93f0d55/HMSegmentedControl/HMSegmentedControl.m#L383

https://github.com/HeshamMegid/HMSegmentedControl/blob/ae84d092891b3e18d89ccc8edae10f2bb93f0d55/HMSegmentedControl/HMSegmentedControl.m#L491

https://github.com/HeshamMegid/HMSegmentedControl/blob/ae84d092891b3e18d89ccc8edae10f2bb93f0d55/HMSegmentedControl/HMSegmentedControl.m#L516

https://github.com/HeshamMegid/HMSegmentedControl/blob/ae84d092891b3e18d89ccc8edae10f2bb93f0d55/HMSegmentedControl/HMSegmentedControl.m#L527

https://github.com/HeshamMegid/HMSegmentedControl/blob/ae84d092891b3e18d89ccc8edae10f2bb93f0d55/HMSegmentedControl/HMSegmentedControl.m#L533

https://github.com/HeshamMegid/HMSegmentedControl/blob/ae84d092891b3e18d89ccc8edae10f2bb93f0d55/HMSegmentedControl/HMSegmentedControl.m#L539

https://github.com/HeshamMegid/HMSegmentedControl/blob/ae84d092891b3e18d89ccc8edae10f2bb93f0d55/HMSegmentedControl/HMSegmentedControl.m#L545

**Comment by yb286278** [comment]
same issue, addBackgroundAndBorderLayerWithRect call many times

**Comment by HeshamMegid** [comment]
This has been fixed on the latest version.
