### ISSUE TITLE
A Question For The Code.

### ISSUE THREAD

**Issue by gzhongcheng** [HeshamMegid/HMSegmentedControl#324]
I used this in my project.
But the distance between the title and the Indicator is too large to cause the text to be centered.
When I read the source code,
I found that you added a descender when calculating the height of text (The `233rd` line in the `HMSegmentedCongrol.m` file).
Why do you want to add this descender?

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
