### ISSUE TITLE
How can I add corner to select segment?

### ISSUE THREAD

**Issue by jihengcong** [HeshamMegid/HMSegmentedControl#331]
![1542357702003](https://user-images.githubusercontent.com/15802247/48612885-301f8000-e9c5-11e8-8eac-a830d0c96aa0.jpg)
@HeshamMegid

**Comment by jihengcong** [comment]
![1542357702003](https://user-images.githubusercontent.com/15802247/48609338-85a45e80-e9be-11e8-860f-d1b778f0aa8f.jpg)

**Comment by HeshamMegid** [comment]
This style is currently not supported.
