### ISSUE TITLE
In the latest version, “setPageScrollView” is not found，why?

### ISSUE THREAD

**Issue by zdmjerry** [HeshamMegid/HMSegmentedControl#333]
/**
 Add animations for scrolling
 */
- (void)setPageScrollView:(UIScrollView *)scrollView; 

about  this method, In the latest version, that is not found，why?

**Comment by MarcSteven** [comment]
Yeah you can do it by yourself @zdmjerry

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. Please feel free to reopen if you're still looking for help.
