### ISSUE TITLE
Crashing on empty data

### ISSUE THREAD

**Issue by vanitaladkat** [HeshamMegid/HMSegmentedControl#335]
I have added HMSegmentedControl in my app. But sometimes its crashing with error (reported with Crashlytics):
** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
-[HMSegmentedControl frameForSelectionIndicator]

Please look into this issue

**Comment by HeshamMegid** [comment]
Can you please post the full stacktrace?

Feel free to reopen when you do.
