### ISSUE TITLE
Section Title Getting Clipped

### ISSUE THREAD

**Issue by adolfdsilva** [HeshamMegid/HMSegmentedControl#336]
Khmer text is getting clipped. 
I tried changing the segment control frame size, but it doesn't help.
I see you have some attribute options like `kCTGlyphInfoAttributeName`, but I can't figure out which one to use or how to use it. Could you help ?

Actual text is 'បញ្ចូលលុយទូរស័ព្ទ' .

<img width="361" alt="Screen Shot 2019-05-06 at 3 14 46 PM" src="https://user-images.githubusercontent.com/6647993/57213988-a6b34700-7012-11e9-9ebd-d15713303c4f.png">

**Comment by HeshamMegid** [comment]
Have you tried adjusting this using an attributed string set via `setTitleFormatter`?

Closing this for now, feel free to reopen if you still need help.
