### ISSUE TITLE
Seperator line at the bottom

### ISSUE THREAD

**Issue by lilin87788** [HeshamMegid/HMSegmentedControl#61]
can you set a property that a Seperator line  at the bottom of segment (which  we can set the Seperator line is hidden and the color of the  Seperator line)?

**Comment by chrise86** [comment]
I think what @lilin87788 means is to have a bar at the bottom of the non-active segment buttons. This would active as a border between the control and the content below.

I too would like this feature :)

**Comment by HeshamMegid** [comment]
Makes sense. I will consider this in a future version.

**Comment by lilin87788** [comment]
sorry for my poor english  O(∩_∩)O~~

**Comment by HeshamMegid** [comment]
Please check the latest commit. This is possible now using `borderType`, `borderColor` and `borderWidth` properties.
