### ISSUE TITLE
not scrollable when both images and titles

### ISSUE THREAD

**Issue by harveyB** [HeshamMegid/HMSegmentedControl#63]
hi,

cool control - good work - thanks!

it was working great when used with images only i.e. it was taking actual image width and enabled horizontal scrolling but when also adding titles, it fits everything into frame width and not allow for scrolling - i set scrollenabled YES and  
segmentWidthStyle = HMSegmentedControlSegmentWidthStyleFixed;
etc. but inside code
  sectionWidth = MAX(stringWidth, imageWidth) 
is not respected and the calculation is off.

in the method
- (void)updateSegmentsRects 
    if ([self sectionCount] > 0) {
        self.segmentWidth = self.frame.size.width / [self sectionCount];
    }
this above line seems to be making the calculation go wrong
- seems like scroll enabled being deprecated is causing the problem

could you plz check
thanks

**Comment by HeshamMegid** [comment]
This should be fixed now. Please check the latest code on master (not available yet as a CocoaPods release) and reopen if it's still not working as expected.
