### ISSUE TITLE
need better effect

### ISSUE THREAD

**Issue by XiangqiTu** [HeshamMegid/HMSegmentedControl#71]
hi，my friend.I notice your Control last year on github and it helps me a lot. thank you for sharing,i like it very much.

i think it can be much better if it has better Interaction design effect. just like NYSegmentedControl on github. while the scrollView didScroll in HMSegmentedControl,the indicatorView changed at once.hm,may be a little difficult to understand....I am sorry that my written English is weak.

haha, thank you for reading my issue.

**Comment by HeshamMegid** [comment]
Sorry for the late reply.

I'm not quite sure I understand what you're trying to do. If you're trying to customize the looks of the selected state of the segments, you can use images as @khan-lau suggested.
