### ISSUE TITLE
FEATURE REQUEST: selectedFont

### ISSUE THREAD

**Issue by peymankh** [HeshamMegid/HMSegmentedControl#72]
Is it possible to add selectedFont property just like selectedTextColor when a segment gets selected?

**Comment by HeshamMegid** [comment]
It seems like a logical thing to have. I'll be working on it soon, or if you would like to implement it and send me a pull request, I would be happy to merge it.

**Comment by jbttn** [comment]
There is already a pull request done which has implemented this... PR #70.  Using text attribute dictionaries makes a lot of sense to me.

**Comment by HeshamMegid** [comment]
This is now available in ca1ae50da39aa2d0a92321fa32a4c7d193998290
