### ISSUE TITLE
Center the selected element all the time including first and last elements?

### ISSUE THREAD

**Issue by Gargo** [HeshamMegid/HMSegmentedControl#73]
your segmented control is so beautiful but I need to place the first and the last elements in the middle when they are selected.
It seems it is enough easy for you to add this as an additional option

**Comment by HeshamMegid** [comment]
If I understand what you want to do correctly, scrolling the first or last segments to the center would mean a lot of white space which would look weird. 

Correct me if I am mistaken.

**Comment by Gargo** [comment]
Yes, I meaned a lot of white space. But I have also found a simple solution with using iCarousel. It has a "linear" style which is exactly I need:
http://2.bp.blogspot.com/-nZr38I9CGfs/TutNZE5oUgI/AAAAAAAAHmU/tAYOZIaV-zc/s1600/111216-0023.png
