### ISSUE TITLE
How to Set Segmented Control BackGround Colour when it is Scrolled?

### ISSUE THREAD

**Issue by ashishgabani** [HeshamMegid/HMSegmentedControl#76]
I am Newbie in iOS Development.I use HMSegmentedControll For my Application it Contain Seven Section Title and i want to Change BackGround Colour of my SegmentedControll When it was Swipe to Next Title How it Possible. If it is Possible then Please Give me Solution?

**Comment by HeshamMegid** [comment]
I don't understand your question. Would you please describe what you want to achieve in a different way?

**Comment by ashishgabani** [comment]
I want to Change Color Of Segmented Controll when next index Selected. I mean when Scrollview Scroll then SegmentedControll BackGround Was Changed Every Time.

**Comment by HeshamMegid** [comment]
How about setting the `backgroundColor` property inside the `indexChangeBlock`?

**Comment by ashishgabani** [comment]
if it is Possible then please Give me Solution.

**Comment by HeshamMegid** [comment]
Something like this:

```
[segmentedControl setIndexChangeBlock:^(NSInteger index) {
    weakSegmentedControl.backgroundColor = [UIColor whateverColor];
}];
```

**Comment by HeshamMegid** [comment]
Something like this:

```
[segmentedControl setIndexChangeBlock:^(NSInteger index) {
    weakSegmentedControl.backgroundColor = [UIColor whateverColor];
}];
```

**Comment by HeshamMegid** [comment]
Something like this:

```
[segmentedControl setIndexChangeBlock:^(NSInteger index) {
    weakSegmentedControl.backgroundColor = [UIColor whateverColor];
}];
```
