### ISSUE TITLE
Can't scroll scroll view when touch starts from HMSegmentedControl

### ISSUE THREAD

**Issue by Rep2** [HeshamMegid/HMSegmentedControl#80]
Hey.

Im using HMSegmentedControl on view with UIScrollView that scrolls content of the view. Everything is working great except I can't scroll view if touch starts from segmented control. 

I think segmented control is receiving scroll event but, as it has no use for it, it just ignores it. Is there any way to forward scroll event from HMSegmentedControl to its superview?

**Comment by HeshamMegid** [comment]
Can you provide some sample code to reproduce this? I've set up a demo project with an `HMSegmentedControl` inside a `UIScrollView` and it's working as expected (scrollview is getting scrolled).
