### ISSUE TITLE
Change size of the buttons with images

### ISSUE THREAD

**Issue by CavalcanteLeo** [HeshamMegid/HMSegmentedControl#81]
I have to set HMSegmentedControl with the 1/2 width of the whole screen, using auto layout. (iphone 5, 6 and 6 plus).

So the width will change according to the screen. and i have fixed sizes of the images.

How to set the button width programmatically and center this images in the center of the buttons

``` objective-c
    NSArray *iconsLeftMenu = [[NSArray alloc]initWithObjects:
                              [UIImage imageNamed:@"icon-timeline"],
                              [UIImage imageNamed:@"icon-map"],
                              nil];

    segmentedControl = [[HMSegmentedControl alloc]
                                             initWithSectionImages:iconsLeftMenu
                                             sectionSelectedImages:iconsLeftMenu];


    segmentedControl.frame = CGRectMake(0, 300, 320, 50);
    // Bellow is the width of the HMSegmentedControl
    CGRect frameMenu = headerLeftView.bounds;
    segmentedControl.frame = frameMenu;

    segmentedControl.backgroundColor = [UIColor clearColor];
    segmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationNone;
    segmentedControl.selectionStyle = HMSegmentedControlSelectionStyleBox;
    [segmentedControl addTarget:self action:@selector(segmentedControlChangedValue:) forControlEvents:UIControlEventValueChanged];
    [headerLeftView addSubview:segmentedControl];
```

![captura de tela 2015-01-22 as 17 11 09](https://cloud.githubusercontent.com/assets/1735944/5862513/bc67a8ba-a259-11e4-9a14-f6a8286c74f2.png)
![captura de tela 2015-01-22 as 17 10 54](https://cloud.githubusercontent.com/assets/1735944/5862512/bc64bf38-a259-11e4-8a43-cf44c08540f0.png)

**Comment by HeshamMegid** [comment]
I'm not sure I understand the problem correctly. Aren't the segments sizes getting set correctly after the AutoLayout constraints have been applied?

**Comment by dctamtn** [comment]
How to change the font-size of menu item text

**Comment by dctamtn** [comment]
??
