### ISSUE TITLE
Cocoapods installs wrong version

### ISSUE THREAD

**Issue by nickbit** [HeshamMegid/HMSegmentedControl#85]
An older version gets installed by adding the pod line to the Podfile, 
Please check!

**Comment by ostatnicky** [comment]
Please! :)

**Comment by gerardp** [comment]
+1

**Comment by FelipeDocil** [comment]
+1

**Comment by HeshamMegid** [comment]
Cocoapods was installing the latest release (1.4). I've included the latest code changes in a new release and labeled it 1.5.

You should get it by updating your pods.
