### ISSUE TITLE
Can not change opacity of indicatorBox

### ISSUE THREAD

**Issue by sdrozzy** [HeshamMegid/HMSegmentedControl#86]
I am using the cocoapod and trying to change the opacity of they indicator box. I have changed its color and opacity to 1.0 but it is giving me a color darker than the one I wanted. I also tried going into the HMSegmentedControl.m and changing the value from the commonInit but it is still not working. Any help would be appreciated.

**Comment by HeshamMegid** [comment]
I believe bb5f2e8ff540966f52abc00d8a111a53cf82235b) adds what you're looking for.
