### ISSUE TITLE
iOS5.1 support

### ISSUE THREAD

**Issue by dvkch** [HeshamMegid/HMSegmentedControl#90]
Hi,

I saw you took extra care in multiple instances to avoid using `-[NSString sizeWithAttributes:]` as to maximise compatibility with older iOS versions. I found a place though where this has been done differently and becomes an issue on iOS 5.1: `HMSegmentedControl.m` lines 226 and 227. The symbol `NSFontAttribueName` doesn't exist on this older version of iOS5 and it makes the app crash on startup because it cannot resolve the external symbol. If you agree to solve this I can recommend those two solutions:

- replacing `NSFontAttributeName` with `kCTFontAttributeName` since they both have the same value 
- using the same macro you do on lines 510, 521, 537, 549:

        #if  __IPHONE_OS_VERSION_MIN_REQUIRED >= 70000

Thanks for considering!

**Comment by HeshamMegid** [comment]
Thanks for reporting this but the latest version completely drops support for iOS 5 and 6.

Feel free to fork an older release and fix for your own use.
