### ISSUE TITLE
Problem with titleTextAttributes in ios 7.1

### ISSUE THREAD

**Issue by gerardp** [HeshamMegid/HMSegmentedControl#92]
Hi,
In ios 7.1 seems that there is a bug setting titleTextAttributes

self.segControl.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor]};
in ios 7.1
![captura de pantalla 2015-03-03 a las 16 24 47](https://cloud.githubusercontent.com/assets/168353/6465712/13b0b3fe-c1c3-11e4-8187-1537bb854707.png)

In ios 8
![captura de pantalla 2015-03-03 a las 16 26 39](https://cloud.githubusercontent.com/assets/168353/6465723/1ce683cc-c1c3-11e4-8298-fd0ebe750975.png)

**Comment by firstim** [comment]
Having same issue on ios 7.0 as well.

**Comment by dinoka** [comment]
Having the same issue.

**Comment by jaumevn** [comment]
Same as @firstim and @dinoka.
Any idea?

**Comment by HeshamMegid** [comment]
Looking into it (and by looking into it I mean downloading the iOS 7.1 simulator :smiley:)...

**Comment by xeravim** [comment]
same here :)

**Comment by HeshamMegid** [comment]
Would you please test the changes in d8e6e4a14024309b6a9c68286d60cf660e4d342b and confirm it solves the problem?

For some weird reason I cannot download the iOS 7 simulator so I'm unable to test it.

**Comment by wynch** [comment]
Yes, this fixes the **CGContextSetStrokeColorWithColor <error>** I was getting on iOS 7.1 (simulator), and the text color is fixed as well

**Comment by HeshamMegid** [comment]
Awesome. Thanks for checking.

**Comment by dinoka** [comment]
Thanks. Issue is fixed now.

**Comment by gerardp** [comment]
Thanks!

**Comment by firstim** [comment]
Thanks, it fixed.
