### ISSUE TITLE
Why the SDK version change?

### ISSUE THREAD

**Issue by shortstuffsushi** [HeshamMegid/HMSegmentedControl#93]
Hi @HeshamMegid, I noticed a [recent commit](https://github.com/HeshamMegid/HMSegmentedControl/commit/ca1ae50da39aa2d0a92321fa32a4c7d193998290) changed the minimum version of the SDK from 5.0 to 7.0. I'm using this nice little component in the [Branch Invite SDK](https://github.com/BranchMetrics/Branch-iOS-Invite-SDK), which has a minimum of 6.0 currently, making it now incompatible with this library :(

Could you explain why you bumped your version support? I glanced briefly through the commit, but was unable to find anything that immediately jumped out as a change requiring the update. I noticed the same issue was raised with #90, but I didn't see the explanation for the change -- could you clarify? Perhaps @leontiy could weigh in, since the changes seem to be part of his pull request.

**Comment by HeshamMegid** [comment]
The new version uses NSString's `sizeWithAttributes:` to calculate the size of segment titles customized via the new `titleTextAttributes`  and `selectedTitleTextAttributes` properties.

Also, it makes sense to drop older iOS versions that have very little usage number and clean the code from all the `__IPHONE_OS_VERSION_MIN_REQUIRED` and duplicated code.

You can lock your pod to version 1.4 if you don't need the new title formatters.

**Comment by shortstuffsushi** [comment]
I was going to argue against that, but I aim to do the same with most of my projects. Supporting the last two versions (8 and 7) seems fair, although [according to MixPanel](https://mixpanel.com/trends/#report/ios_frag), 6 still has 15% market share. [Apple claims](https://developer.apple.com/support/appstore/) as little as 3%. At any rate, at some point you have to drop support, so I guess that's ok.

**Comment by HeshamMegid** [comment]
The difference in numbers between Apple and MixPanel is interesting. I personally think Apple's way of measuring it is a more realistic indicator of which phones are actively being used to download new apps.
