### ISSUE TITLE
Invalid Context Error

### ISSUE THREAD

**Issue by xrolfex** [HeshamMegid/HMSegmentedControl#97]
When using the control on iOS  7.1 you get an Invalid context on CGContextSetStrokeColorWithColor when using swift.

<Error>: CGContextSetFillColorWithColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by HeshamMegid** [comment]
This has been fixed in d8e6e4a.

**Comment by xrolfex** [comment]
Got it, missed that that fix was after the 1.5 tag that cocoapods podspec uses.
