### ISSUE TITLE
Segments doen't get direct touch

### ISSUE THREAD

**Issue by DrAma999** [HeshamMegid/HMSegmentedControl#98]
First I'd like to thank you for sharing this control.
I'm experiencing this pretty weird issue using xcode 6.2 and ios8.2, the issue is the the same on device and simulator.
When I try to press a single segment the touch isn't detected.
Digging through your code I've found that (here are getting weird) the scrollview is eating touches even if I'm not dragging the touch is not sent to the next responder. The weird thing is that if I put a break point inside the touchesBegan method of the scroll view the touch is then sent to the next responder and everything works.
Frames seem to be correct so I'm not thinking about an out of frame problem.

Here is how I'm configuring the segmented:
`control.backgroundColor = [UIColor clearColor];`
`control.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationNone;`
       ` control.selectionStyle = HMSegmentedControlSelectionStyleTextWidthStripe;`
       ` control.userDraggable = NO;`
      `  control.segmentEdgeInset = UIEdgeInsetsMake(0, 2, 0, 2);`

**Comment by HeshamMegid** [comment]
I've tried to set up a control with the same properties and it seems to be working fine.

Could you please create a sample project that reproduces this issue?

**Comment by btrzupek** [comment]
I am seeing the exact same thing. @DrAma999 did you ever resolve this?

**Comment by DrAma999** [comment]
No, but telling you the truth the project that is using it is freezed. If it will start again and the problem is still present in iOS9 I will change it.
As far as I remember the problem was present only while debugging.

**Comment by btrzupek** [comment]
I actually figured out my issue. I had a tapGestureRecognizer on the main view for the view controller. That was eating the taps for the control.
