### ISSUE TITLE
Feature Update

### ISSUE THREAD

**Issue by jsetting32** [HeshamMegid/HMSegmentedControl#99]
Would be awesome if while scrolling a UIScrollView, that the segmentedControl line scrolls with it.

**Comment by HeshamMegid** [comment]
Do you mean that the selected segment would be changed automatically as you scroll?

**Comment by jsetting32** [comment]
No that is already implemented I feel. What I mean to say is while your scrolling the UIScrollView the segment line scrolls as well. So currently, when the UIScrollView is done scrolling, you check which page its on and set the segment to that index. But I feel that it would be awesome if the segment control would move as the scroll view moves. For example, when the app loads, the segment index would be set to 0 of course, as well as the scrollview’s page. Assume there are 3 pages, like in the example. So the first page is selected as well as the first segment. Now the user starts to scroll to the second page but hasn’t released, so scrollViewDidEndDecelerating: hasn’t fired yet. But while the user scrolls, the segment control line (bar) scrolls as your scrolling to the next page. 

I feel that scrollViewDidScroll: would need to be implemented of course.

I think the algorithm would go a little something like this:

- (void)scrollViewDidScroll:(UIScrollView)scrollView
{
	float scrollViewWidthSize = scrollView.contentSize.width;

	float currentSegmentBarPosition = self.segmentBar.bar.origin;
	currentSegmentBarPosition = scrollViewWidthSize / numberOfPages or numberOfSegments;
	self.segmentBar.bar.origin = currentSegmentBarPosition;
}

Sorry, i know this method won’t work but I figure its something to give you a hint of what I’m thinking. I guess make the bar for the segmentControl public and implement the scrollViewDidScroll: method to be able to modify the position of the bar. 

And just to clarify, what I mean by ‘bar’ is the little line under the text of the selected segment control index.

Hopefully this clears things up.

**Comment by HeshamMegid** [comment]
Thanks for the explanation, it's clear now. I've been wanting to do this for a while but I haven't had the time yet.

Feel free to have a go at it and send me a pull request.

**Comment by HeshamMegid** [comment]
Closing this issue for now since it was opened a very long time ago. 

If you'd still like to see this, feel free to open a PR.
